export const ChoanalAtresia = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "Please describe this image",
      sample_answer: "This is a CT scan in an axial view showing bilateral obstruction at the level of the choanae. My differential diagnosis would be biltaral choanal atresia.",
    },
    {
      question: "How would you expect this child to present?",
      sample_answer: "I would expect a child with bilateral choanal atresia to present with significant respiratory distress immediately after birth. Given that neonates are obligate nasal breathers until at least 2 to 6 months old, bilateral atresia would compromise their ability to breathe, leading to symptoms such as nasal flaring, suprasternal retractions, and cyanosis. These symptoms might temporarily improve when the baby cries, as crying opens the mouth, allowing for air passage. Feeding difficulties would also be prominent due to the baby's struggle to coordinate sucking and breathing simultaneously.",
    },
    {
      question: "How would you expect a child with unilateral choanal atresia to present?",
      sample_answer: "A child with unilateral choanal atresia typically presents later in life compared to bilateral cases, as one patent nasal passage can still facilitate breathing. The most common symptoms include unilateral rhinorrhea and nasal obstruction, which might be initially attributed to more common conditions like allergies or infections. Over time, the persistent and unilateral nature of these symptoms might raise suspicion for choanal atresia. Additionally, there might be reports of difficulty with nasal breathing on the affected side or anosmia. These symptoms are often less acute and may not be detected until the child experiences recurrent sinus infections or persistent nasal congestion unresponsive to standard treatments.",
    },
    {
      question: "What would you inquire about during your history taking for this patient?",
      sample_answer: "In my history taking, I would inquire about: Birth and Early Neonatal Period: Any complications during delivery, Apgar scores, immediate postnatal distress, and any interventions required soon after birth. Respiratory Symptoms: The presence of respiratory distress, cyclical cyanosis, and any improvement with crying. For older children, specifics about nasal breathing difficulties or episodes of apnea. Feeding History: Difficulties with feeding, especially in neonates, including whether the infant can feed without becoming cyanotic or breathless. Nasal Symptoms: Episodes of rhinorrhea, whether it's unilateral or bilateral, nasal congestion, and any prior interventions or treatments attempted. Systemic Symptoms and Development: Any signs of developmental delay, growth retardation, or other systemic symptoms that might suggest an associated syndrome like CHARGE. Family History: Any similar conditions in the family or other congenital anomalies, to understand if there's a genetic pattern or predisposition.",
    },
    {
      question: "What would you look for during your examination of this patient?",
      sample_answer: "During my examination, I would assess for: Signs of Respiratory Distress: Including nasal flaring, cyanosis, and whether symptoms improve with crying, indicating possible bilateral atresia. Nasal Obstruction: Attempting to pass a 6 or 8 french catheter or NG tube through the nostrils to detect any blockage, which would be indicative of atresia. I can also observe for misting on a cold spatula or perform flexible nasendoscopy with a paediatric FNE. External Features: Observing for any external ear and eye abnormalities, such as small or abnormally shaped pinnae and colobomas, which could suggest a syndromic association like CHARGE. Facial and Oral Examination: Looking for midline defects, palatal anomalies, or other facial dysmorphologies that might indicate a syndromic condition. Respiratory System Examination: For signs of increased work of breathing or retractions, which would corroborate the history of respiratory distress.",
    },
    {
      question: "What investigations would you undertake for this patient?",
      sample_answer: "For a patient suspected of having choanal atresia, I would undertake: Nasal Endoscopy: To directly visualize the choanae and confirm the presence and type of atresia. Computed Tomography (CT) Scan: This provides detailed anatomical information, defining the extent of the atresia, whether it is bony, membranous, or mixed, and assists with surgical planning. Genetic Testing: If syndromic features are present, to identify conditions like CHARGE syndrome, which can inform the management approach and prognosis. Cardiac Screening: An echocardiogram is essential for detecting any congenital heart defects that may be associated with syndromic cases of choanal atresia. Renal Ultrasound: To check for any renal anomalies, as part of the comprehensive assessment for associated syndromes.",
    },
    {
      question: "What is choanal atresia?",
      sample_answer: "Choanal atresia is a congenital condition characterized by the blockage of the choanae, which are the posterior nasal apertures that connect the nasal cavity to the nasopharynx. This blockage results from the failure of the bucconasal membrane to rupture or due to abnormal bony growth and, or, membranous growth during embryonic development. It may present as unilateral or bilateral, with unilateral cases being more common but often less symptomatic early in life. The obstruction can be classified as bony, membranous, or most commonly, a mix of both types around 70% of the time. The condition has an incidence of about 1 in 7,000 live births, with a slight predilection for females and the right side. Approximately 50% of cases are associated with other congenital syndromes, most notably CHARGE syndrome.",
    },
    {
      question: "What are your differential diagnoses for neonatal nasal obstruction?",
      sample_answer: "Differential diagnoses for neonatal nasal obstruction include: Pyriform Aperture Stenosis: A congenital narrowing of the nasal entrance that can cause respiratory distress. Nasal Septal Deviation: Although usually presenting with milder symptoms, it could be congenital due to birth trauma. Nasal Cavity Masses: Such as teratomas, encephaloceles, or dacrocystoceles, which physically block the nasal passages. Neonatal Rhinitis: Inflammation of the nasal mucosa leading to obstruction. Encephalocele: A rare neural tube defect presenting with a nasal mass and obstruction.",
    },
    {
      question: "What conditions are choanal atresia associated with?",
      sample_answer: "CHARGE Syndrome: The most common concurrent syndrome in bilateral atresia, characterized by a cluster of congenital anomalies. 22q11 Deletion Syndrome Craniosynostosis Syndromes: Such as Crouzon and Apert syndromes, which involve premature fusion of skull sutures. Treacher Collins Syndrome Trisomy 21 (Down Syndrome) and Trisomy 18 (Edwards Syndrome)",
    },
    {
      question: "What is CHARGE syndrome?",
      sample_answer: "CHARGE syndrome is a genetic disorder characterized by a specific set of birth defects that affect various systems of the body. The acronym 'CHARGE' stands for: Coloboma: A defect in the eye structure, which may include part of the iris, retina, or eyelid, potentially leading to vision problems. Heart defects: Congenital heart anomalies of various types, which can affect the heart's structure and function. Atresia of the Choanae: Blockage or narrowing of the nasal passages, which can lead to breathing difficulties, especially in newborns who are obligate nasal breathers. Retardation of growth and/or development: Delayed growth and development, affecting height, weight, and cognitive and motor skills. Genitourinary abnormalities: Problems with the formation of the genitalia and urinary system, which can range from minor anomalies to more significant malformations. Ear abnormalities and deafness: Hearing loss (which can be sensorineural, conductive, or mixed), structural ear anomalies, and problems with balance. The prevalence of CHARGE syndrome is estimated to be about 1 in 10,000 to 15,000 births. It is caused by mutations in the CHD7 gene on chromosome 8, which is important for the development of many parts of the body. Most cases of CHARGE syndrome are due to new (de novo) mutations in the CHD7 gene, meaning they occur spontaneously and are not inherited from the parents.",
    },
    {
      question: "How would you manage this child?",
      sample_answer: "Management of a child with choanal atresia is a multidisciplinary endeavour, which involves: Immediate Airway Management: For bilateral atresia, securing the airway through the placement of an oropharyngeal airway or, in severe cases, intubation, is paramount. Feeding Assistance: Addressing feeding difficulties with specialized techniques or equipment such as a mcgovern nipple to assist with feeding while ensuring adequate nutrition. Surgical Interventions include endoscopic transnasal, endoscopic transoral and a combination of the two. The transpalatal approach is no longer used owing to an increased risk of velopharyngeal insufficiency and fistulation. Surgical correction aims to establish a patent airway and resolve the obstruction. The Multidisciplinary Approach is crucial, Especially in cases with associated syndromic features, involving genetics, cardiology, ophthalmology, and other relevant specialties to address the comprehensive needs of the patient",
    },
    {
      question: "Describe your surgical approach to treating this condition.",
      sample_answer: "I begin with preoperative planning, thoroughly reviewing the CT scan to assess the anatomy and extent of the choanal atresia to help me plan my approach. The patient is then appropriately anaesthetised and positied in a reverse trendelenburg position to reduce venous pressure and minimize operative bleeding. The nose is then prepped with topical decongestants within the nasal passages to reduce mucosal bleeding, ensuring a clear operative field. This also aids in gently dilating the nasal passages for better access and visualization. In a tonsillectomy set up, with a boyle davis gagg and drafin rods, I insert a 120-degree Hopkins rod endoscope intraorally, aiming towards the nasopharynx to visualize the posterior aspect of the choanal atresia from a retropalatal perspective. I can then use fine instruments like a urethral dilator, make a gentle initial perforation in the atretic plate, predominantly focusing on the area that appears thinnest or most amenable to penetration, and then removing the plate with tools such as drills. If there is a significant bony component I may have to go transnasal to do a posterior septectomy. It is important to Meticulously manage the nasal mucosa to cover any exposed bony surfaces, promoting healing and reducing the likelihood of adhesions and re-stenosis. This involves careful repositioning of any mucosal flaps created during the procedure. Post operatively, the child needs saline, decongestant and steroid drops.",
    },
    {
      question: "In what cases would you use a stent as part of your surgery?",
      sample_answer: "I would consider using a stent in the surgical management of choanal atresia in cases where there is a high risk of re-stenosis, such as when a significant portion of the choanal passage has been obstructed or altered, and in children with CHARGE as they will be undergoing other procedures for their condition. Stenting might also be considered in cases where the structural integrity of the nasal passage is compromised, and additional support is deemed necessary to maintain patency during the healing process. However, the decision to use a stent would be made cautiously, taking into account the potential risks of stent-related complications such as mucosal damage, infection, columellar necrosis, alar notching, granulation, circumferential scarring and discomfort for the patient. The lack of strong consensus on the benefits of stenting requires a careful consideration of each case's unique aspects, discussing the potential risks and benefits with the parents or guardians to make an informed decision tailored to the patient's specific needs and circumstances.",
    },
    {
      question: "What would you tell the patient's parents of a child undergoing surgery during the consent process?",
      sample_answer: "During the consent process, I would explain that the surgery aims to correct the anatomical defect causing their child's breathing and feeding difficulties. The benefits include resolving these difficulties, potentially eliminating the need for alternative breathing and feeding aids, and improving the child's overall quality of life. The risks involve the possibility of re-stenosis, requiring further intervention, bleeding, infection, midfacial growth arrest, nasal saddling, skull base injury and risks associated with general anesthesia. I would also discuss the potential need for stenting and its associated risks, such as discomfort and risk of infection. Alternatives to surgery and the expectation for postoperative care, including the importance of follow-up visits for endoscopic evaluations, would be detailed.",
    },
  ],
};
