export const Cholesteatoma = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "A patient presents with ear discharge and reduced hearing. What would be your differential diagnosis for this?",
      sample_answer: "I would consider the following differential diagnoses categorized by etiology: Infectious Causes: Acute and Chronic Otitis Media including cholesteatoma, Malignant Otitis Externa Traumatic Causes: Tympanic Membrane Perforation due to trauma or barotrauma Neoplastic Causes: Temporal Bone SCC, Exostoses, Osteomas Miscellaneous Causes: Eustachian Tube Dysfunction leading to effusion, Foreign Body in the External Auditory Canal",
    },
    {
      question: "What would you inquire about during your history taking for this patient?",
      sample_answer: "I would ask about: Symptom Chronology: Onset, duration, and progression of ear discharge and hearing loss to differentiate between acute and chronic conditions. Previous Ear Infections and Surgeries: History of ear infections, surgeries, or interventions like grommet insertion, which might predispose to complications such as cholesteatoma. Pain: Presence or absence of pain can help differentiate between conditions like acute otitis media (typically painful) and cholesteatoma (often painless). Tinnitus and Vertigo: Indications of inner ear involvement or extensive middle ear disease. Facial Weakness: Suggesting possible facial nerve involvement, which can occur with extensive cholesteatoma. Systemic Symptoms: Fever, malaise, or symptoms of upper respiratory tract infections that might accompany or precede otologic symptoms. Impact on Daily Life: Effects on hearing, communication, work, or school performance to assess the functional impact of the ear condition. Nasal Symptoms: Such as congestion or drainage, indicating possible Eustachian tube dysfunction contributing to middle ear disease.",
    },
    {
      question: "What would you look for during your examination of this patient?",
      sample_answer: "During the physical examination, I would perfrom External Ear Examination: Checking for discharge, inflammation, signs of otitis externa, or visible foreign bodies. Otoscopy: Assessment of the tympanic membrane for perforations, retraction pockets, presence of cholesteatoma as a pearly white mass, granulation tissue, polyps, and the condition of the ossicles if visible. Also, the extent of discharge and its characteristics. Neurological Examination: Evaluation of cranial nerve function, especially the facial nerve (CN VII), for any signs of weakness or paralysis. Hearing Assessment: Basic bedside tests like whisper test, tuning fork tests (Rinne and Weber) to evaluate the type and degree of hearing loss. Vestibular Function: Tests for dizziness or vertigo, including the fistula test to see if a cholesteatoma is suspected to have eroded into the inner ear structures.",
    },
    {
      question: "This is what you see on otoscopy. Please describe it.",
      sample_answer: "This is an otoendoscopic image of a left ear with collection of keratinised debris in the attic region. This is suspicious for cholesteatoma, and indeed, I can see some fullness behind the posterior aspect of the drum which I suspect to be part of the sac extending towards the mastoid. I would like to perform Otomicroscopy to better visualise of the tympanic membrane and middle ear space.",
    },
    {
      question: "What is cholesteatoma?",
      sample_answer: "This is a collection of migrating keratinising squamous epithelium in the middle ear and/or mastoid cavity. It is also known as active squamous chronic otitis media, and there are 10 cases per 100 000 a year, with 10% of cases being bilateral.",
    },
    {
      question: "What are the types of cholesteatoma?",
      sample_answer: "Cholesteatoma can be classified into three main types: Primary Acquired, Secondary Acquired and Congenital cholesteatoma. Primary Acquired Cholesteatoma: The most common type, often associated with chronic Eustachian tube dysfunction leading to retraction pockets in the tympanic membrane that accumulate keratin debris. It is usually located in the posterior epitympanum, followed by posterior mesotympanum and anterior epitympanim. Posterior epitympanic cholesteatoma migrates to the epitympanum and posterior mesotympanum lateral to the ossicles. Posterior mesotympnanic cholesteatoma migrates to the mastoid, medial to the ossicles and involves the facial recess. Anterior epitympanic cholesteatoma migrates to the supratubal recess and involves the geniculate ganglion. Secondary Acquired Cholesteatoma: Results from the direct invasion of the middle ear by squamous epithelium through a pre-existing perforation or secondary to surgery or trauma. Congenital Cholesteatoma: Arises from embryonic epithelial cells that become trapped within the middle ear space, presenting as a white mass behind an intact tympanic membrane, often in an anterosuperior location.",
    },
    {
      question: "What are the etiological theories of primary acquired cholesteatoma?",
      sample_answer: "The etiological theories of primary acquired cholesteatoma include: Retraction Pocket Formation: Due to Eustachian tube dysfunction, leading to negative pressure in the middle ear and retraction of the tympanic membrane. Basal Cell Hyperplasia Theory: Suggests that hyperplasia of basal cells of the tympanic membrane epithelium leads to the formation of cholesteatoma. Squamous Metaplasia Theory: Chronic inflammation causes metaplasia of the middle ear mucosa into squamous epithelium, contributing to cholesteatoma formation. Epithelial Migration Theory: Abnormal migration of the squamous epithelium through an existing perforation in the tympanic membrane forms cholesteatoma.",
    },
    {
      question: "How is chronic otitis media classified?",
      sample_answer: "It is broken down into mucosal and squamous chronic otitis media, which can both active or inactive. Active squamous disease refers to cholesteatoma, whilst inactive squamous disease is a retraction pocket. Active mucosal disease refers to a discharging perforation, whilst inactive mucosal disease is a dry perforation.",
    },
    {
      question: "What investigations would you undertake for a patient with cholesteatoma?",
      sample_answer: "I would undertake the following investigations: Pure Tone Audiometry (PTA): To evaluate the type (conductive, sensorineural, or mixed) and degree of hearing loss. Cholesteatomas typically cause conductive hearing loss, but sensorineural components may arise if the inner ear is involved. High-Resolution Computed Tomography (CT) of the Temporal Bones: This is Essential for anatomical evaluation and showing the extent of disease.",
    },
    {
      question: "What do you look for on your CT of the temporal bones?",
      sample_answer: "In terms of extent of disease on a CT of the temporal bones, I look for scutum erosion, ossicular erosion especially of the long process of the incus, mastoid involvement, and any petrous apex involvement. For surgical anatomy considerations, I assess mastoid pneumatisation to understand Eustachian tube function early in life, which informs surgical approach decisions. Ventilation status of the middle ear and mastoid air cells highlights current Eustachian tube function, influencing procedure choices. I evaluate the ear canal's bony thickness, particularly near the temporomandibular joint and mastoid air cells, crucial for canalplasty. The presence and size of an emissary vein are noted to prevent bleeding. Sigmoid sinus position and its relationship to the mastoid affect the feasibility of posterior tympanotomy. A high-riding or dehiscent jugular bulb is identified to prevent intraoperative complications. Carotid artery dehiscence, particularly near the Eustachian tube, is checked to avoid vascular injury. The shape and position of the tegmen tympani are evaluated for risks like encephalocoele or cholesteatoma extending into the middle cranial fossa. The condition of the facial nerve, especially in revision surgeries, is crucial to avoid nerve damage. Lastly, identifying a lateral semicircular canal fistula is critical to prevent vestibular complications during surgery.",
    },
    {
      question: "How would you manage a patient with cholesteatoma?",
      sample_answer: "Management of a patient with cholesteatoma primarily involves surgical intervention, aiming to eradicate the disease, restore hearing, create a safe dry ear and prevent recurrence. This can be done by a variety of surgical approaches, with my preference being canal wall down mastoidectomy where feasible. In certain cases, especially in elderly or unfit patients, conservative management involving regular aural toilet, topical antibiotic drops for infections and monitoring may be considered, but the primary treatment is surgical.",
    },
    {
      question: "What are the surgical options for a patient with cholesteatoma?",
      sample_answer: "These can broadly described as endoscopic vs microscopic, canal wall up vs canal wall down and back to front vs front to back. My familiarity is with the combined approach, canal wall up mastoidectomy, which preserves the posterior ear canal wall but may require a second-look surgery to check for residual disease, and the canal wall down mastoidectomy approach, which removes the posterior ear canal wall, creating an open cavity that reduces the risk of residual disease but requires more post-operative care.",
    },
    {
      question: "In what situations would you prefer to perform a combined approach tympanoplasty as opposed to a canal wall down mastoidectomy?",
      sample_answer: "A combined approach tympanoplasty (CAT) Preserves posterior and superior EAC walls, providing a self cleaning, water safe ear that can accomodate hearing aids, whilst a Canal Wall Down Mastoidectomy involves removal of the posterior and superior external auditory canal walls to create a single cavity that combines the ear canal and mastoid. This approach facilitates drainage and access for cleaning but may require more maintenance. I prefer a CAT in cases where there is Limited disease, with relieable patient follow up and suitability for further surgery if required, as there is increased risk of undectected recurrence or residual cholesteatoma. A canal wall down mastoidectomy on the other hand is Recommended for extensive disease, when there's a high risk of recurrence, or in cases where patient follow-up is uncertain. It is also suitable for difficult to reach areas not adequately addressed by a canal wall up procedure, or indeed in revision cases.",
    },
    {
      question: "What factors lead to a persistently discharging mastoid cavity postoperatively?",
      sample_answer: "Factors leading to a persistently discharging mastoid cavity postoperatively include: Inadequate matoplasty: Perforation of the neotympanum: Incomplete Removal of Disease: Leaving residual cholesteatoma or infected tissue can perpetuate discharge. Poor Cavity Design: Inadequate saucerization of the cavity can lead to poor epithelialization and accumulation of debris. High Facial Ridge: Can hinder proper drainage and aeration of the cavity. Large Cavity Size: Larger cavities are more difficult to keep clean and dry, increasing the risk of recurrent infection. Eustachian Tube Dysfunction: Continued dysfunction can lead to middle ear effusions and discharge through the mastoid cavity.",
    },
    {
      question: "In what situations would you obliterate the mastoid? And how do you do it?",
      sample_answer: "Obliterating the mastoid cavity is considered in situations such as: Poor Mastoid Aeration and Pneumatization: To reduce the size of the cavity and its maintenance needs. Recurrent or Aggressive Cholesteatoma: To minimize the risk of recurrence by eliminating dead spaces where disease can redevelop. Significant Cavity Maintenance Issues: For patients having difficulty with post-operative cavity care leading to recurrent infections or discomfort. Methods of Mastoid Obliteration include: Using Autologous Materials: Such as bone pate, fat, cartilage, or muscle to fill the cavity. Synthetic Materials: Hydroxyapatite or bioactive glass can also be used. Myosubcutaneous Flaps: Particularly in larger cavities, using vascularized tissue can provide a robust method for obliteration, reducing cavity size and maintenance requirements.",
    },
    {
      question: "What are the considerations for cholesteatoma in children?",
      sample_answer: "Considerations for managing cholesteatoma in children include: Aggressive Nature of Pediatric Cholesteatoma: Requires prompt and complete removal to prevent complications. Preservation of Hearing: Emphasis on techniques that allow for the potential restoration or preservation of hearing, considering the impact on language development and education. Surgical Approach: Preference towards less invasive approaches when feasible and consideration of future growth and development of the ear structures. Long-Term Monitoring: Due to the high recurrence rate in children, meticulous follow-up with regular audiometry and imaging is crucial for early detection of recurrence.",
    },
    {
      question: "What would you do if this was the patient's only hearing ear?",
      sample_answer: "In the scenario of cholesteatoma in the patient's only hearing ear, I would: Prioritize Hearing Preservation: Opt for surgical approaches that maximize the chance of preserving or improving hearing, such as a cautious canal wall up approach or limited dissection around critical structures. Consider Non-Surgical Management: In select cases, careful monitoring and conservative management may be considered to preserve hearing, especially if the cholesteatoma is small and not causing significant issues. Counseling: Discuss extensively with the patient the risks and benefits of surgery versus conservative management, considering the potential impact on their quality of life and hearing. Plan for Rehabilitation: Preoperative planning for hearing rehabilitation, including the use of hearing aids or cochlear implants, depending on the outcome of the surgical intervention.",
    },
    {
      question: "What would you do if you saw some cholesteatoma overlying a dehiscent lateral semicircular canal intraoperatively?",
      sample_answer: "If cholesteatoma is observed overlying a dehiscent lateral semicircular canal, I would: Leave that area until last, and then utilise delicate dissection techniques to remove the cholesteatoma without disrupting the delicate membranous labyrinth. An alternative is to apply KTP laser to this area. If it was the patient's only hearing ear, I would potentially leave it there and then monitor the patient closely for recurrence. If it wasn't an only hearing ear, I would consider a canal wall down approach for easier monitoring. If the fistula is small and not actively leaking perilymph, I would consider covering it with soft tissue, such as bone pate or temporalis fascia, without aggressive manipulation. Post operatively I would Prepare the patient for the possibility of postoperative vertigo and hearing changes, closely monitoring for these complications.",
    },
    {
      question: "How do you monitor for recurrence?",
      sample_answer: "Monitoring for recurrence of cholesteatoma involves: Regular Otoscopic Examination: For direct visualization of the ear canal and middle ear space for any signs of retraction, debris accumulation, or visible cholesteatoma. Follow-Up Audiometry: To detect changes in hearing levels that may suggest recurrent disease. Imaging Studies: Non-EPI DW MRI is particularly valuable for detecting cholesteatoma recurrence due to its high sensitivity and specificity for cholesteatoma. It's recommended at regular intervals post-surgery or if symptomatic recurrence is suspected. Patient Education: Informing patients about the signs of recurrence and the importance of regular follow-up visits for early detection and management.",
    },
    {
      question: "What are your considerations for ossicular chain reconstruction?",
      sample_answer: "Ossiculoplasty timing and decision-making are influenced by: Disease Eradication: Performed after complete cholesteatoma removal and ensuring a disease-free middle ear to prevent graft becoming a recurrence site. Middle Ear Condition: Requires a dry, infection-free ear; ossiculoplasty risks graft failure in damp or infected conditions. Surgical Approach: May occur during canal wall up procedures if favorable, or be delayed in canal wall down approaches for a stable ear environment. Hearing Needs: Prioritized for significant hearing loss, especially in the better-hearing ear, based on patient's preoperative hearing status. Patient Expectations: Consideration of the patients lifestyle and hearing restoration priorities. Ossicle Viability: Utilizes patients own disease-free ossicles when available; alternatively, employs synthetic or prosthetic materials. Second-look Surgery: Offers a chance for ossiculoplasty assessment if not done initially, especially during canal wall up approaches with planned follow-up for residual disease checking",
    },
    {
      question: "How do you perform a mastoidectomy?",
      sample_answer: "Performing a mastoidectomy involves several key steps: Having reviewed the preoperative CT scan, in an appropriately consented, positioned and anaesthetised patient, with a facial nerve monitor in place, I infiltrate the post auricular area with lidocaine with adrenaline and then place my incision 1cm behind the post auricular sulcus and Elevate skin flap towards the external ear canal, cutting through postauricular muscle to reach temporalis fascia. I create an anteriorly based periosteal flap and use a raspatory to elevate the flap until the spine of henlé is visible. I identify mcewan's triangle, formed by the inferior temporal line superiorly, the postero-superior wall of the EAC anteriorly and a line drawn between them posteriorly, and then Begin drilling into the mastoid cortex, using a 5mm cutting burr with continuous suction-irrigation to clear bone dust and maintain a clear surgical field. I Progressively remove mastoid air cells, initially delineating the tegmen and sigmoid sinus, then thinning the posterior canal wall, as I work deeper, through Korner's septum and into the antrum. I then work to identify my lateral semicircular canal and short process of incus before switching to a 2mm diamond burr to perform a posterior tympanotomy.",
    },
    {
      question: "What are the complications of cholesteatoma?",
      sample_answer: "Cholesteatoma complications can be categorized based on the area affected, ranging from local to more severe intracranial consequences. Heres a breakdown: Local Complications: Ossicular Chain Erosion: Leads to conductive hearing loss by damaging the bones that transmit sound to the inner ear. Tympanic Membrane Perforation: Persistent or enlarging perforations due to the expanding cholesteatoma. Chronic Otorrhea: Persistent ear discharge resulting from recurrent infections. Inner Ear Complications: Labyrinthine Fistula: Erosion into the inner ear, potentially causing sensorineural hearing loss and vertigo. Sensorineural Hearing Loss: Can occur if the cholesteatoma or its removal damages the cochlea. Facial Nerve Complications: Facial Nerve Paralysis: The cholesteatoma can erode the bony canal housing the facial nerve, leading to paralysis or dysfunction. Intracranial Complications: Meningitis: Infection can spread to the meninges surrounding the brain. Brain Abscess: Collection of pus within the brain tissue, a severe life-threatening condition. Extradural Abscess: Accumulation of pus between the dura mater and the skull. Lateral Sinus Thrombosis: Clot formation in the lateral sinus due to infection spread, potentially leading to increased intracranial pressure and intracranial abscess. Extracranial Complications: Mastoiditis: Infection spreading to the mastoid bone, leading to inflammation and possible abscess formation. Subperiosteal Abscess: A collection of pus that forms under the periosteum of the mastoid bone. Bezolds Abscess: A deep neck infection that occurs when cholesteatoma leads to mastoiditis and the infection spreads into the neck.",
    },
  ],
};
