export const congenitalHearingLoss = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "Please describe this audiogram",
      sample_answer: "This is a pure tone audiogram showing a cookie-bite, mid-frequency sensorineural hearing loss on the left side. This is characteristic of congenital hearing loss.",
    },
    {
      question: "This is an audiogram of a 2 year old boy. What are the important aspects in the history?",
      sample_answer: "When assessing a child with congenital hearing loss, important historical aspects include the onset and progression of hearing loss, speech and language development, any associated symptoms such as balance issues or visual problems, and family history of hearing loss or consanguinity. Prenatal history should also be considered, including maternal infections, substance use, and any complications during pregnancy. Perinatal history, including conditions such as prematurity, NICU admission, hyperbilirubinemia, and use of ototoxic medications, provides critical insights. Additionally, a thorough review of the child’s medical history for trauma, surgery, any related syndromic features or other medical conditions such as those affecting the cardiac, neurologic, and renal systems is essential. It is also important to enquire about their results in the newborn hearing screening.",
    },
    {
      question: "What are the important aspects in the examination of a child with congenital hearing loss?",
      sample_answer: "The examination of a child with congenital hearing loss should include a detailed otologic examination, including inspection of the outer ear for any abnormalities, otoscopy to examine the ear canal and tympanic membrane, and assessments of middle ear function such as tympanometry. A general physical examination to identify any syndromic features or other physical anomalies is also critical. This may include examining the eyes, the craniofacial structure, the skin (for café-au-lait spots or pigmentation anomalies), and the neck (for goiter or branchial cleft anomalies). Vestibular examination and assessment of overall development and neurological status are also important components of the examination.",
    },
    {
      question: "What investigations would you carry out in a child with congenital hearing loss?",
      sample_answer: "I would follow the 2018 British Association of Audiovestibular Physicians guidelines, for investigating congenital hearing loss. In this, investigations are categorized into Level 1 (mandatory) and Level 2 (conditional based on specific indications) investigations: Level 1 Investigations include Audiological Assessment such as otoacoustic emissions (OAE), auditory brainstem response (ABR), and behavioral audiometry when age-appropriate. Genetic Testing: Testing for Connexin 26 and Connexin 30 gene mutations due to their common link with nonsyndromic hearing loss. Imaging: High-resolution CT of the temporal bones and MRI of the internal auditory meatus and brain to identify structural anomalies. Infectious Workup: CMV testing using saliva or urine samples for CMV DNA PCR to check for congenital CMV infection. Ophthalmological Examination which is Essential due to the potential association of hearing loss with ocular abnormalities. Electrocardiogram (ECG): To exclude syndromes with cardiac manifestations. Renal Ultrasound: Recommended if syndromes like Branchio-Oto-Renal (BOR) syndrome are suspected. Level 2 Investigations: Initiated based on specific clinical findings from Level 1 investigations or particular family history, including more detailed genetic panels, autoimmune disease testing, and further imaging studies if initial results suggest additional anomalies.",
    },
    {
      question: "Which subjective tests do you employ for children?",
      sample_answer: "Subjective audiometric testing is chosen based on the child's age and cognitive abilities to accurately assess hearing levels. These include: Birth to 6 months: Behavioral Observation Audiometry (BOA) is used, observing the child's behavior in response to sounds. 6 months to 2 years: Visual Reinforcement Audiometry (VRA) involves teaching the child to turn towards a sound source, reinforced visually by a toy or video. 2 to 5 years: Conditioned Play Audiometry (CPA) makes the hearing test a game where the child performs an action, like placing a block in a box, in response to hearing a tone. 5 years and older: Conventional Pure Tone Audiometry (PTA) becomes feasible, where the child responds to tones through headphones by raising a hand or pressing a button.",
    },
    {
      question: "Unfortunately this child was missed by the newborn hearing screening as they came from another country. Can you please outline the newborn hearing screening program and its pathways?",
      sample_answer: "There are two pathways, the Well Baby Pathway and the NICU Pathway. The Well Baby Pathway begins with the Automated Otoacoustic Emission (AOAE) screening test. If there is no clear response, a second AOAE test is performed. If there is still no clear response, the Automated Auditory Brainstem Response (AABR) screening test is administered. A referral for immediate audiological assessment is made if there isn't a clear response from the AABR test. Babies with risk factors, despite passing the second AOAE, are referred for audiological assessment at 7 to 9 months of age to ensure any late-onset hearing loss is identified. The NICU Pathway focuses on babies who have been in NICU for more than 48 hours, acknowledging their higher risk of hearing loss. These babies receive both AOAE and AABR screening tests. The outcome dictates the next steps, which can range from discharge from the service to immediate referral for audiological assessment if there is a no clear response or risk factors present. Babies with no clear response from both the AOAE and AABR are referred for audiological assessment within 4 weeks of screen completion or by 44 weeks corrected age. Similarly those with an inconclusive response on AABR. Those with risk factors but normal AABR are also referred for audiological assessment at 7 to 9 months of age. For both pathways, if parents do not consent to the screening, they are provided with checklists to monitor their baby’s hearing development and informed to consult with a GP or health visitor. Contraindications to testing includes atresia/microtia, bacterial meningitis, confirmed cCMV, or a programmable shunt. These patients are referred directly for audiological assessment within 4 weeks or by 44 weeks gestational age.",
    },
    {
      question: "what are the risk factors?",
      sample_answer: "The risk factors for hearing loss in newborns that warrant a targeted audiological follow-up at 7 to 9 months of age, even if they pass the newborn hearing screening, include: Family history of permanent childhood hearing impairment. Neonatal intensive care of more than 48 hours. Apgar score of 0 to 4 at 1 minute or 0 to 6 at 5 minutes. Mechanical ventilation required for more than 24 hours. In utero infections such as CMV, toxoplasmosis, and herpes. Craniofacial anomalies that affect the head and structure of the ear. Syndromes associated with hearing loss (e.g., Down syndrome, Usher syndrome). Neurodegenerative disorders. Postnatal infections that could affect hearing, such as bacterial meningitis. Hyperbilirubinemia at a level requiring exchange transfusion. These risk factors are closely monitored because they are associated with a higher likelihood of developing hearing loss after the initial newborn screening period, indicating the need for ongoing vigilance and assessment to ensure early detection and intervention.",
    },
    {
      question: "Tell me about OAE and ABR tests",
      sample_answer: "OAEs, either as Transitory Otoacoustic Emissions (TOAEs) using a series of clicks or tones, or as Distortion Product Otoacoustic Emissions (DPOAEs), using two continuous tones, measure sound waves produced by the outer hair cells of the cochlea in response to auditory stimuli. These emissions are an indicator of the cochlea's health, specifically the outer hair cells. If these cells are functioning properly, they generate sounds in response to an acoustic stimulus, which can be measured with a microphone placed in the ear canal. The presence of OAEs typically suggests normal cochlear (outer hair cell) function, whereas their absence may indicate hearing loss or cochlear dysfunction. However, OAEs alone cannot determine the type or degree of hearing loss. ABR testing, on the other hand, evaluates the auditory nerve's response to sound and the brain's pathway up to the brainstem. This test uses electrodes placed on the head to measure the electrical activity generated by the auditory pathway in response to sound. It's particularly useful for estimating hearing sensitivity and identifying neurological abnormalities affecting auditory nerve and brainstem function. Abnormal or absent ABR responses may suggest neural dysfunction in the auditory pathway, even when cochlear function (as indicated by OAEs) is normal, a condition often seen in Auditory Neuropathy Spectrum Disorder (ANSD).",
    },
    {
      question: "Tell me about the ABR Waves",
      sample_answer: "ABRs have five to seven distinct waves, traditionally labeled I through VII, occurring within the first 10 milliseconds after an auditory stimulus is presented. These waves represent neural activity from different points along the auditory pathway, from the cochlea up through the brainstem. Wave 1 originates from the distal portion of the Eighth nerve. Wave 2 is generated by the cochlear nucleus. Wave 3 reflects activity from the superior olivary complex. Wave 4 is believed to arise from the lateral lemniscus Wave 5 reflects the inferior colliculus. Waves 6 and 7 are less consistently observed. The timing (latency) and amplitude of these waves provide information about the auditory pathway's integrity and function. Children usually only have walves 1, 3 and 5.",
    },
    {
      question: "What are the criteria for cochlear implantation in children in the UK?",
      sample_answer: "For children in the UK, simultaneous bilateral cochlear implantation is recommended as an option for those with severe to profound deafness who do not receive adequate benefit from acoustic hearing aids. The criteria for 'adequate benefit' are based on speech, language, and listening skills appropriate to the child's age, developmental stage, and cognitive ability.",
    },
    {
      question: "What is congenital hearing loss?",
      sample_answer: "Congenital hearing loss refers to hearing impairment that is present at birth. It may result from genetic factors, contributing to approximately 50% of cases, or from non-genetic factors such as infections during pregnancy, birth complications, prematurity, and maternal drug use. The incidence of congenital hearing loss is estimated to be between 1 to 3 in 1000 live births. This type of hearing loss can be categorized into hereditary (genetic) and acquired types. Hereditary hearing loss might be part of a syndrome affecting other organs or systems (syndromic) or might only affect hearing (nonsyndromic). Most genetic hearing loss follows an autosomal recessive pattern, but autosomal dominant, X-linked, and mitochondrial inheritance patterns are also observed. Acquired congenital hearing loss is often related to prenatal factors like infections (e.g., CMV, rubella) or maternal substance abuse, as well as perinatal factors such as hypoxia or hyperbilirubinemia.",
    },
    {
      question: "Tell me about heriditary hearing loss",
      sample_answer: "Hereditary hearing loss is a type of hearing impairment that has a genetic basis and can be present at birth or develop later in life. It accounts for about half of all congenital hearing loss cases. This form of hearing loss may be syndromic, where the hearing loss is associated with other symptoms or conditions, or nonsyndromic, where the hearing loss occurs in isolation. Approximately 70% of hereditary hearing loss is nonsyndromic, and about 80% of these cases follow an autosomal recessive inheritance pattern. The most common genetic cause of nonsyndromic hearing loss is mutations in the Connexin 26 gene (GJB2), though many other genes are also involved. Syndromic hearing loss, on the other hand, is part of genetic syndromes affecting multiple organs, such as Usher syndrome (hearing loss and vision loss) and Pendred syndrome (hearing loss and thyroid dysfunction).",
    },
    {
      question: "Tell me about the acquired causes of hearing loss.",
      sample_answer: "Acquired causes of hearing loss in children include those arising from infections, environmental factors, and ototoxic medications. Infections such as bacterial meningitis, measles, and mumps can lead to sensorineural hearing loss. Environmental factors include exposure to loud noise or head trauma. Ototoxic medications, such as certain antibiotics (aminoglycosides) and chemotherapy drugs, can damage the inner ear. Additionally, conditions like otitis media can cause conductive hearing loss if not properly managed. Each of these causes can affect hearing to varying degrees, from mild impairment to profound deafness, and may involve one or both ears.",
    },
    {
      question: "What are the autosomal dominant causes of congenital hearing loss?",
      sample_answer: "The autosomal dominant causes of congenital hearing loss can be remembered using the mnemonic 'WANT CBS', which stands for: Waardenburg syndrome: Characterized by pigmentary abnormalities of the skin, hair, and eyes, dystopia canthorum (widely spaced inner corners of the eyes), and varying degrees of hearing loss. Apert syndrome: Known for craniosynostosis (premature fusion of skull bones), syndactyly (fusion of digits), and sometimes associated with conductive hearing loss due to middle ear abnormalities. Neurofibromatosis type 2 (NF2): Presents with bilateral vestibular schwannomas (tumors on the nerves leading to the inner ear) that can lead to progressive hearing loss. Treacher Collins syndrome: Features facial anomalies including underdeveloped facial bones, and hearing loss, usually conductive, due to malformations of the external and middle ear. Crouzon syndrome: Causes craniosynostosis leading to abnormal skull shape; hearing loss, if present, is typically conductive. Branchio-oto-renal (BOR) syndrome: Involves branchial arch anomalies, renal anomalies, and hearing loss that can be sensorineural, conductive, or mixed. Stickler syndrome: Affects collagen production leading to ocular, articular, and orofacial abnormalities, with sensorineural hearing loss often part of the clinical picture.",
    },
    {
      question: "What are the autosomal recessive causes of congenital hearing loss?",
      sample_answer: "Autosomal recessive causes of congenital hearing loss typically result in nonsyndromic hearing loss, with the most common genetic cause being mutations in the Connexin 26 gene (GJB2). Other conditions include Usher syndrome, which combines hearing loss with retinitis pigmentosa; Pendred syndrome, associated with hearing loss and thyroid dysfunction; and Jervell and Lange-Nielsen syndrome, featuring profound deafness and cardiac arrhythmias.",
    },
    {
      question: "Tell me about cochlear anomalies.",
      sample_answer: "Cochlear anomalies refer to structural abnormalities of the cochlea, which can lead to sensorineural hearing loss. These anomalies can vary widely, from complete aplasia (Michel deformity) to more subtle defects like incomplete partitioning (e.g., Mondini dysplasia). Common cochlear anomalies include Mondini dysplasia, characterized by an incomplete number of cochlear turns and an enlarged vestibular aqueduct; and Scheibe dysplasia, involving the membranous labyrinth with normal bony structure. Cochlear anomalies may occur as isolated defects or as part of syndromic conditions, such as Pendred syndrome or CHARGE syndrome. Diagnosis is often achieved through imaging, such as high-resolution CT or MRI, which helps in identifying the specific type of anomaly and guiding management and treatment options, including the potential for cochlear implantation in some cases.",
    },
    {
      question: "Tell me about enlarged vestibular aqueduct.",
      sample_answer: "Enlarged vestibular aqueduct (EVA) is a condition where the vestibular aqueduct, a bony canal that connects the inner ear to the cranial cavity, is larger than normal. This can lead to sensorineural hearing loss, which may be fluctuating or progressive. EVA is one of the most common inner ear anomalies associated with sensorineural hearing loss in children. Symptoms can include hearing loss, vertigo, and balance disturbances. The exact cause of EVA is not well understood, but it can occur in isolation or be associated with other inner ear abnormalities, such as Pendred syndrome. Diagnosis is typically made through imaging studies, such as CT or MRI scans, and management focuses on monitoring hearing and preventing further hearing loss, as there is currently no cure for the condition",
    },
  ],
};
