export const DifferentiatedThyroidCancer = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "You have a 45 year old patient presenting with an anterior neck lump you suspect to be coming from the thyroid. What are the types of thyroid neoplasms?",
      sample_answer: "I understand that the primary types of thyroid neoplasms include well-differentiated thyroid cancers, such as Papillary Thyroid Carcinoma (PTC) and Follicular Thyroid Carcinoma (FTC), which are the most common forms of thyroid cancer. PTC accounts for about 80% of all thyroid malignancies and is known for its association with previous radiation exposure and its tendency to spread to lymph nodes. Less than 1 cm in size, it's referred to as a papillary microcarcinoma, which is often adequately treated with a hemithyroidectomy. FTC, on the other hand, is notable for its hematogenous spread, being the second most common type of thyroid cancer, and its differentiation from adenomas depends on capsular invasion. Hurthle Cell Carcinoma, previously considered a variant of FTC, is recognized for its worse prognosis compared to FTC. Anaplastic Thyroid Cancer, an undifferentiated form of thyroid cancer, is particularly aggressive, rapidly progressing, and predominantly affects the elderly with a very poor prognosis. Medullary Thyroid Cancer (MTC) originates from the parafollicular C cells, with a portion being genetic, involving conditions such as MEN 2A and 2B syndrome. Finally, Lymphoma of the thyroid, while less common, is diagnosed through biopsy methods like core or open biopsy.",
    },
    {
      question: "What would you inquire about during your history taking for this patient?",
      sample_answer: "In my history taking, I would delve into the onset and progression of symptoms, particularly focusing on swallowing or airway difficulties and voice changes, as these symptoms can suggest the mass's impact on surrounding structures. I'd inquire about any personal and family medical history related to autoimmune thyroid diseases or previous exposure to radiation, which could predispose the patient to thyroid cancer. Specifically, a detailed family history regarding thyroid cancer or genetic syndromes associated with an increased risk of thyroid cancer, such as Multiple Endocrine Neoplasia syndromes, would be essential. Furthermore, understanding the patient's exposure to potential risk factors, such as a diet deficient in iodine or previous history of head and neck radiation, is crucial for a comprehensive risk assessment",
    },
    {
      question: "What would you look for during your examination of this patient?",
      sample_answer: "During the examination, I would assess the size, location, and characteristics of the thyroid nodule or nodules, noting whether the nodule moves with swallowing, which would suggest its attachment to the thyroid gland, indicative of its intrathyroidal location. Palpation for cervical lymphadenopathy would be performed to identify potential metastatic disease. A thorough examination of the neck for signs of retrosternal extension of the thyroid gland or any evidence of tracheal deviation would be essential. Additionally, I would conduct a flexible nasolaryngoscopy to evaluate vocal cord function, as involvement or compression of the recurrent laryngeal nerve by the thyroid mass could lead to vocal cord paralysis, an important sign of advanced disease",
    },
    {
      question: "What investigations would you undertake for this patient?",
      sample_answer: "For a patient presenting with an anterior neck swelling, I would initially undertake thyroid function tests to assess the thyroid's functional status. Calcitonin and carcinoembryonic antigen (CEA) levels would be specifically measured if medullary thyroid cancer is a consideration, given their role as tumor markers for this type of cancer. Ultrasound scanning of the thyroid would be the primary imaging modality to assess the nodule's characteristics, guiding the need for fine-needle aspiration cytology (FNAC) based on specific ultrasound findings indicative of malignancy. FNAC, guided by ultrasound, would then be performed to obtain cytological samples from the nodule, which is crucial for diagnosing thyroid cancer. Depending on the initial findings and suspicion for medullary thyroid cancer or the presence of suspicious lymph nodes, additional imaging such as CT of the neck and chest might be undertaken for further evaluation and staging. I would discuss any suspicious or cancer cases in my local thyroid MDT.",
    },
    {
      question: "What is the U grading?",
      sample_answer: "The U grading system refers to the ultrasound grading of thyroid nodules based on their appearance on ultrasound imaging. This grading system helps in assessing the risk of malignancy of thyroid nodules, ranging from U1, indicating a normal thyroid gland, U2 being a benign gland, U3 being indeterminate, U4 being suspicious and U5, which is almost certainly a malignancy. A variety of features suggest malignancy, including: Hypoechoic Texture: Malignant nodules often appear hypoechoic or darker compared to the surrounding thyroid tissue. Irregular Margins: Malignant nodules may have irregular, lobulated, or poorly defined borders, suggesting invasion into surrounding tissues. Microcalcifications: These are tiny calcium deposits within the nodule, appearing as bright white spots on ultrasound. Microcalcifications are highly suggestive of papillary thyroid cancer. Taller-than-wide Shape: A nodule that is taller than it is wide (measured in a transverse view) is more likely to be malignant. This orientation suggests an abnormal growth pattern. Solid Composition: While cystic nodules are often benign, solid or predominantly solid nodules have a higher risk of malignancy. Absent or Incomplete Halo: A peripheral rim of sonolucent (dark) tissue, known as a halo, is often seen around benign nodules. An absent or incomplete halo can suggest malignancy. Increased Intranodular Vascularity: Doppler ultrasound showing increased blood flow within a nodule can indicate malignancy, as cancerous nodules often develop new blood vessels (neoangiogenesis). Presence of Central Vascularity: The distribution of blood flow within the nodule, especially when the flow is predominantly central, may suggest a higher likelihood of cancer. Enlarged Cervical Lymph Nodes: The presence of abnormal or metastatic lymph nodes in the neck, especially if they are hypoechoic, have calcifications, or have a rounded shape, can indicate the spread of thyroid cancer.",
    },
    {
      question: "What is the thy grading?",
      sample_answer: "Thy grading refers to the cytological classification system for evaluating thyroid fine-needle aspiration cytology (FNAC) results. It goes from Thy1, indeterminate to thy 5, malignant, cytology. Thy1 is Non-diagnostic or unsatisfactor,y, indicating The sample does not contain enough cells to make a diagnosis. Thy1c Indicates a non-diagnostic sample that is cystic. A Thy2 sample shows features consistent with a benign nodule, such as colloid nodules or benign thyroid hyperplasia. The risk of malignancy is very low, approximately 0-3%. Thy3a refers to Atypia of undetermined significance or follicular lesion of undetermined significance - AUS/FLUS. This sample shows atypical cells that don't clearly suggest malignancy or benignity. The risk of malignancy ranges from approximately 5-15%. Further investigation, such as repeat FNAC or molecular testing, may be recommended. Thy3f refers to a Follicular neoplasm which cannot be distinguished from follicular carcinoma without histological evidence of capsular or vascular invasion. The risk of malignancy ranges from about 15-30%. Thy4 is Suspicious for malignancy. This sample has cellular features suggestive of malignancy, but not definitive. The risk of malignancy is high, approximately 60-75%. Thy5 is Malignant cytology. The sample shows definitive cytological features of malignancy, corresponding to one of the specific types of thyroid cancer. The risk of malignancy is very high, around 97-100%.",
    },
    {
      question: "What do you do if your FNAC comes back as Thy3a?",
      sample_answer: "If the FNAC result comes back as Thy3a, indicating 'neoplasm possible' with atypia or being non-diagnostic, further investigation is required due to the indeterminate nature of this result. This could involve additional diagnostic imaging, such as a repeat ultrasound to reassess the nodule's characteristics, and possibly a repeat FNAC to attempt to get a more definitive cytological diagnosis. Depending on the clinical scenario and the patient's risk factors, proceeding to a diagnostic hemithyroidectomy may be recommended to obtain a histopathological diagnosis, as this approach allows for the comprehensive evaluation of the nodule",
    },
    {
      question: "What does thy3f mean?",
      sample_answer: "Thy3f in the FNAC grading system indicates a 'follicular neoplasm,' suggesting the presence of a follicular thyroid neoplasm. This category implies that the cytology shows features suggestive of a follicular pattern, which could potentially be either a benign follicular adenoma or a follicular carcinoma, a distinction that cannot be made cytologically due to the requirement of examining the capsule for invasion to diagnose carcinoma. Therefore, patients with a Thy3f result typically proceed to a diagnostic hemithyroidectomy, allowing for histological examination of the entire nodule and its capsule to accurately differentiate between benign and malignant follicular lesions",
    },
    {
      question: "You perform a hemithyroidectomy for a thy3a lesion and the histology confirms papillary thyroid cancer. How do you proceed?",
      sample_answer: "Upon confirming papillary thyroid cancer through histological examination after a hemithyroidectomy for a Thy3a lesion, the next steps in management would depend on the cancer's specific characteristics, such as tumor size, presence of multifocality, lymphovascular invasion, and the presence of lymph node or distant metastases. In cases where the tumor is small, intrathyroidal, and without aggressive features, the remaining thyroid lobe may be sufficient, and further surgery might not be necessary. However, for larger tumors, those with aggressive features, or evidence of spread, completion thyroidectomy might be recommended to remove the remainder of the thyroid tissue. This would facilitate postoperative radioactive iodine ablation if indicated, along with thyroxine replacement therapy to maintain euthyroid status and suppress TSH to minimize the risk of recurrent disease. The decision would be tailored based on a thorough discussion in a multidisciplinary team setting and considering the patient's preferences and overall health.",
    },
    {
      question: "Outline the T staging for thyroid cancers.",
      sample_answer: "T staging for thyroid cancers, as per the AJCC/UICC TNM classification, describes the size and extent of the primary tumor. T1 tumors are ?2 cm in greatest dimension and confined to the thyroid. T1a is ?1 cm, and T1b is >1 cm but ?2 cm. T2 tumors are >2 cm but ?4 cm without extrathyroidal extension. T3 tumors are >4 cm or have minimal extrathyroidal extension. T4a tumors invade subcutaneous soft tissues, larynx, trachea, esophagus, or recurrent laryngeal nerve, indicating moderately advanced disease. T4b tumors invade prevertebral fascia or encase carotid artery or mediastinal vessels, representing very advanced disease.",
    },
    {
      question: "Outline the N staging for thyroid cancers",
      sample_answer: "N staging for thyroid cancers reflects the extent of regional lymph node metastasis. N0 indicates no regional lymph node metastasis. N1a involves metastasis to level VI (pre-tracheal, para-tracheal, and pre-laryngeal/delphian) lymph nodes. N1b indicates metastasis to unilateral, bilateral, or contralateral cervical or retropharyngeal or superior mediastinal lymph nodes.",
    },
    {
      question: "What factors would lead you to perform a total thyroidectomy rather than a hemithyroidectomy in a patient with differentiated thyroid cancer?",
      sample_answer: "Factors leading to a total thyroidectomy rather than a hemithyroidectomy in differentiated thyroid cancer include a tumor size greater than 4 cm, aggressive histological variants, bilateral disease, multifocal disease, extrathyroidal extension, presence of distant metastasis, and significant lymph node involvement. Additionally, a patient's history of radiation exposure or familial predisposition to thyroid cancer, as well as the presence of certain genetic mutations, might also necessitate a more aggressive surgical approach. Total thyroidectomy facilitates postoperative radioactive iodine ablation and more accurate monitoring using thyroglobulin levels.",
    },
    {
      question: "What are the postoperative indications of radioactive iodine?",
      sample_answer: "Postoperative indications for radioactive iodine (RAI) therapy include tumors larger than 4 cm, extrathyroidal extension, vascular invasion, aggressive histological subtypes, incomplete surgical resection, presence of distant metastases, and significant lymph node involvement. RAI is utilized to ablate remnant thyroid tissue, eradicate microscopic disease, and treat or prevent metastatic spread. The decision for RAI therapy is made based on individual risk assessment and discussed within the multidisciplinary team.",
    },
    {
      question: "When would you perform a neck dissection in differentiated thyroid cancer?",
      sample_answer: "A neck dissection in differentiated thyroid cancer is performed when there is clinically evident lymph node metastasis (N1), either preoperatively or intraoperatively identified. Therapeutic neck dissection is indicated for clinically positive nodes, while prophylactic central neck dissection (level VI) may be considered in patients with papillary thyroid carcinoma with advanced primary tumors, due to a high risk of microscopic lymph node metastasis. Lateral neck dissection (levels II-V) is performed for clinically involved lateral cervical lymph nodes. The extent of neck dissection is tailored to the pattern of disease spread and involves a careful balance between oncologic control and preserving function, particularly regarding the recurrent laryngeal nerves and parathyroid glands.",
    },
    {
      question: "What is dynamic risk stratification?",
      sample_answer: "Dynamic risk stratification (DRS) is a methodology used post-treatment to reassess the individual risk of recurrence or persistent disease in patients with differentiated thyroid cancer. It is done 9 months after surgery for patients who have have RAI and total thyroidectomy. DRS takes into account the patient's response to initial therapy, including surgical resection and radioactive iodine ablation, as well as subsequent thyroglobulin levels and imaging studies. Patients are categorized into groups reflecting their risk of recurrence or persistent disease: excellent response, indeterminate response, or incomplete response. This stratification informs subsequent management decisions, tailoring the intensity of surveillance and need for additional treatments to the patient's current disease status.",
    },
    {
      question: "What are the prognostic scores in differentiated thyroid cancer?",
      sample_answer: "Prognostic scoring systems in differentiated thyroid cancer, such as the TNM staging, MACIS (Metastasis, Age, Completeness of resection, Invasion, Size), and AGES (Age, Grade, Extent, Size), help predict the patient's outcome and guide treatment decisions. These systems take into account factors such as the patient's age, tumor size, extent of disease, histological grade, and the presence of metastases. High-risk categories often include older age, male gender, larger tumor size, extrathyroidal extension, and distant metastases. These scoring systems enable clinicians to classify patients into low-, intermediate-, or high-risk groups for recurrence or mortality, facilitating personalized treatment planning and follow-up.",
    },
    {
      question: "How would you manage this case if it was medullary thyroid cancer?",
      sample_answer: "For medullary thyroid cancer (MTC), the management involves total thyroidectomy with central neck dissection, given MTC's origin from parafollicular C cells and its potential for early lymphatic spread. Preoperative evaluation should include measurement of calcitonin and carcinoembryonic antigen (CEA) levels, RET proto-oncogene testing for familial forms, and screening for associated endocrinopathies in the context of MEN syndromes. Prophylactic lateral neck dissection may be considered if there is evidence of lymph node involvement. Postoperatively, monitoring involves serial measurements of calcitonin and CEA to assess for disease persistence or recurrence. Treatment decisions, particularly regarding the extent of surgery and the need for additional interventions, are guided by a multidisciplinary team approach.",
    },
    {
      question: "What is the role of PET CT in differentiated thyroid cancer?",
      sample_answer: "Positron emission tomography-computed tomography (PET CT), particularly using fluorodeoxyglucose (FDG), plays a role in differentiated thyroid cancer primarily in the postoperative setting for patients with elevated thyroglobulin levels but negative radioiodine scans. This scenario suggests the presence of disease that has lost the ability to concentrate iodine, thus becoming radioiodine-refractory. PET CT can help localize metastatic or recurrent disease not visible on conventional imaging, guide further therapeutic decisions, and is especially useful in assessing the disease's aggressiveness and prognostication. Its role is complemented by other imaging modalities and clinical assessment in a comprehensive evaluation of the patient's disease status.",
    },
    {
      question: "What is the significance of a Non-invasive follicular thyroid neoplasm with papillarylike nuclear features (NIFTP) ?",
      sample_answer: "NIFTP represents a distinct entity with unique pathological characteristics, prognosis, and implications for clinical management: NIFTP was reclassified from being considered a form of low-risk papillary thyroid carcinoma (PTC) due to its very low potential for aggressive behavior and metastasis. This reclassification reflects its follicular growth pattern with encapsulation or clear demarcation and the presence of nuclear features reminiscent of PTC but without capsular or vascular invasion. NIFTP has an excellent prognosis with a very low risk of recurrence or metastasis when completely resected. This favorable outlook is primarily because NIFTP does not exhibit the invasive properties seen in traditional forms of thyroid cancer. The recognition of NIFTP has significant implications for the clinical management of patients. The diagnosis encourages a more conservative surgical approach, often avoiding the need for total thyroidectomy and radioactive iodine treatment, which are typically considered for more aggressive thyroid cancers. Instead, a lobectomy may be sufficient for managing NIFTP, reducing the potential for overtreatment and associated complications or side effects. Given its low-risk nature, patients diagnosed with NIFTP may require less intensive post-operative surveillance compared to those with more aggressive thyroid cancers. However, careful histopathological evaluation is crucial to differentiate NIFTP from other thyroid neoplasms that may require more aggressive treatment. The diagnosis of NIFTP is based on strict histopathological criteria, underscoring the importance of accurate pathological assessment. The criteria include a well-circumscribed, encapsulated follicular lesion with no capsular or vascular invasion and specific nuclear features.",
    },
  ],
};
