export const Epiglottitis = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "You are called at home by your registrar who is reviewing a 2 year old with a 24 hour history of worsening stridor. What is your differential diagnosis for presentation?",
      sample_answer: "The differential diagnosis for pediatric acute airway obstruction, such as stridor, can be broadly categorized into infectious, anatomical, and lesion-based causes: Infectious Causes: Acute Laryngotracheobronchitis is Most common infectious cause, primarily subglottic, caused by parainfluenza, influenza, rhinovirus, RSV, adenovirus. Bacterial Tracheitis, this is Superinfection following viral URI. pathogens include S. aureus, Group A Streptococcus, S. pneumoniae, H. influenzae. Epiglottitis, this is characterised by Sudden onset, high fever, drooling, caused by Haemophilus influenzae type b, S. pneumoniae, S. pyogenes, S. aureus. Anatomical Causes include Vocal Cord Paralysis which can be Unilateral or bilateral, congenital or acquired. Laryngeal Web, which is Associated with 22q11 deletion syndrome. Tracheo-Esophageal Fistula of which there are Various types including oesophageal atresia with or without TOF. Laryngeal Cleft which refers to Failure of oesophagotracheal ridges to fuse, and has an aspiration risk. Subglottic Stenosis which is a Congenital or acquired narrowing of the subglottis. Vascular Rings can lead to Compression of trachea/esophagus. Lesions include Recurrent Respiratory Papillomatosis, a condition of Benign neoplasia caused by HPV types 6 and 11. Sugblottic Hemangiomas can cause obstruction. And lastly, Foreign Bodies can be aspirated, causing Sudden onset of symptoms.",
    },
    {
      question: "What questions do you ask while on the phone to assess a child with worsening stridor?",
      sample_answer: "I would enquire about Onset and Duration: When did the stridor start, and how has it progressed? Fever: Is there any fever or signs of infection? Cough: Is there a cough, and if so, what type (barky, dry, productive)? Breathing Difficulty: Any signs of increased work of breathing, such as retracting or nasal flaring? Voice Changes: Any changes in the voice or cry of the child? Swallowing Difficulty or Drooling: Is the child able to swallow saliva or fluids without difficulty? Previous Medical History: Any previous episodes like this, recent illnesses, surgeries, or known allergies? Vaccination Status: Is the child up-to-date with vaccinations, including Hib and DTP?",
    },
    {
      question: "What would you like your registrar to do while you are on your way to the patient?",
      sample_answer: "I would like them to move the child to the paediatric resuscitation bay and call the senior most paediatric anaesthetist available as well as the paediatric intensive care teams. It is important to keep the child and parents calm and reassured, avoiding any procedures that might cause distress. If possible, we should Ensure a primary assessment focusing on the ABCs without causing distress to the child. I would advise Provide high-flow oxygen, nebulised adrenaline as 1ml of 1 in 1000 adrenaline made up to 5ml with normal saline and oral dexamethasone at 0.15 to 0.3mg/kg orally, ensuring to minimize distress and Keep the child in a comfortable position, preferably upright or in the parent's arms, to aid breathing. I would also ask them to Prepare for potential airway intervention, gathering the necessary equipment, including a tracheostomy set. We should continue to closely monitor vital signs, oxygen saturation, and signs of respiratory distress.",
    },
    {
      question: "What is stridor?",
      sample_answer: "Stridor is a high-pitched, wheezing sound caused by disrupted airflow, usually due to partial obstruction of the upper airway. It can be inspiratory, expiratory, or biphasic, indicating the level of airway obstruction: Inspiratory Stridor: Suggests supraglottic or glottic obstruction. Expiratory Stridor: More common with lower airway obstruction. Biphasic Stridor: Indicates a fixed obstruction at or near the glottis.",
    },
    {
      question: "What are the differences between the pediatric airway and that of an adult?",
      sample_answer: "The differences include: Size and Shape: Pediatric airways are smaller and the larynx is positioned higher (C3-C4 in children vs. C6 in adults). The infant's epiglottis is larger and more omega-shaped. Subglottic Region: The narrowest part of the pediatric airway is the subglottis, whereas in adults, it's the glottis. Anatomical Features: Children have a relatively larger tongue and a smaller, more flexible trachea, contributing to increased risk of airway obstruction. Immaturity: The pediatric airway structures are less rigid and more susceptible to collapse and swelling.",
    },
    {
      question: "Upon arrival in Paeds resus, how will you manage this patient?",
      sample_answer: "Management should follow the APLS algorithm, emphasizing the importance of a structured approach to assessment and intervention: Airway (A): In ensuring the airway is patent, I would Look for signs of obstruction such as drooling and listen for stridor while avoiding causing any distress or worsening obstruction. This will help me determine if we need to secure the airway. Breathing (B): I would Assess breathing adequacy, looking for tachypnoea, cyanosis, tracheal tug, subcostal recession, nasal flaring, head bobbing and checking for desaturation. I would auscultate the chest for wheeze, air entry and crackles. If not already done, I would Provide high-flow oxygen, nebulized adrenaline and oral dexamethasone. Circulation (C): I would Check for tachcardia and signs of dehydration. Disability (D): I would Evaluate consciousness using the AVPU scale (Alert, Voice, Pain, Unresponsive) as well as tiredness to see if the patient is tiring. Environment (E): I would assess for any signs of trauma, rash, or other findings while maintaining warmth to prevent hypothermia.",
    },
    {
      question: "The patient was sitting in the tripod position, with signs of increased work of breathing, but he has responded to nebulised adrenaline. How are you going to investigate this patient?",
      sample_answer: "If it is not going to distress the child, I would consider a lateral neck x ray and a chest x ray to help identify signs of epiglottitis i.e. the thumb sign, croup i.e. the steeple sign, retropharyngeal abscess and any lung pathology or foreign body.",
    },
    {
      question: "This is your lateral neck radiograph. After initial improvement, the patient is deteriorating. What is the diagnosis and how are you going to treat this patient?",
      sample_answer: "The thumb sign on a lateral neck radiograph is indicative of acute epiglottitis, a life-threatening infection causing swelling of the epiglottis leading to airway obstruction. Immediate treatment focuses on securing the airway in theatre through coordination with our anaesthetics team and administering appropriate antibiotics.",
    },
    {
      question: "How are you going to secure the patient's airway?",
      sample_answer: "Securing the airway, especially in the context of pediatric acute airway obstruction such as epiglottitis, requires careful planning and a strategic approach. Initially, the steps include: Preparation; I would Gather all necessary equipment and personnel, including a pediatric anesthesiologist and ENT surgeon, with a full range of airway management tools (laryngoscopes, various sizes of endotracheal tubes, and a tracheostomy set) in theatre. Positioning: We would Position the child to maximize airway patency, often sitting up or in the 'sniffing' position, unless contraindicated. Oxygenation: We would Provide high-flow oxygen via a method that minimizes distress, such as blow-by oxygen, while preparing for further intervention. Visual Assessment and Attempted Intubation: We would Use the least invasive method first, such as direct laryngoscopy under spontaneous breathing, to assess the airway obstruction and attempt intubation if the airway view is adequate. If not possible, we will proceed to attempt intubation with an appropriately sized ET tube sheathed over a hopkins rod. For this, we will keep the child spontaneously ventilating with sevoflurane delivered via a nasopharyngeal tube, I will use a parson's paediatric endoscope to perform laryngoscopy and pass my ET Tube sheathed hopkins rod into the airway once I obtain a view, and secure it once in the trachea. I am aware this can also be done with a ventilating bronchoscope and bougie or LMA with flexible laryngoscope.",
    },
    {
      question: "Initial attempts with direct laryngoscopy and hopkins rod have failed to secure the airway, and this is what you are seeing. How will you secure the airway now?",
      sample_answer: "This is an endoscopic photograph showing a swollen epiglottis and minimal airway. Given the failure to secure the airway so far, I would consider a tracheostomy. I am aware that in the absence of an otolaryngologist, our anaesthetic colleagues may consider an emergency cricothyroidotomy.",
    },
    {
      question: "Lets say you successfully secured the airway with a Hopkins rod and now have a tube in place. What are your next steps?",
      sample_answer: "After successful intubation, the focus shifts to comprehensive management and stabilizing the patient including: Infection Control: I would Take a swab from the epiglottis for culture. We would Administer broad-spectrum IV antibiotics, starting with ceftriaxone and metronidazole, to cover potential pathogens until culture results guide specific treatment. Supportive Care: We would Ensure IV access for fluids to maintain hydration and administer medications as well as sending appropriate bloods. We would Monitor vital signs and oxygen saturation closely in a PICU setting. Anti-inflammatory Treatment would be in the form of IV dexamethasone to reduce inflammation and edema in the airway. Sedation would be useful To ensure the patient's comfort and prevent dislodgement of the tube on PICU. Once stabilized, we would plan for extubation, which includes assessing airway edema reduction, ensuring normal respiratory function, and possibly repeating laryngoscopy to confirm readiness for extubation.",
    },
    {
      question: "How do you determine when to take out the ET tube and wake the child up?",
      sample_answer: "This can be considered after a period of 24 to 48 hours if there patient develops a cuff leak, to indicate reduction in the swelling and I would consider direct laryngoscopy to confirm this. If other paramaters such as vital signs, alertness, responsiveness and protective reflexes are appropriate, we would then extubate.",
    },
    {
      question: "What is the microbiology of epiglottitis?",
      sample_answer: "The microbiology of epiglottitis has evolved with vaccination practices, but the primary pathogens include: Haemophilus influenzae type b (Hib) was Historically the most common cause of epiglottitis. The introduction of the Hib vaccine has significantly reduced its incidence. Streptococcus pneumoniae is An important pathogen, especially in cases where Hib is not the cause. Streptococcus pyogenes (Group A Streptococcus) Can cause epiglottitis along with other upper respiratory infections. Staphylococcus aureusm, Including methicillin-resistant S. aureus (MRSA), can be a cause, especially in adults and immunocompromised individuals.",
    },
    {
      question: "How would your management have differed if this had been your X ray result?",
      sample_answer: "The steeple sign on neck radiography is indicative of croup, characterized by subglottic swelling leading to a narrowed airway profile. Management focuses on symptomatic relief and preventing progression: Corticosteroids: Dexamethasone is administered orally or intramuscularly to reduce airway inflammation. Nebulized Epinephrine: For moderate to severe croup presenting with significant stridor at rest or distress, nebulized epinephrine can reduce airway swelling. Humidified Oxygen: Provides relief for mild croup, though its effectiveness is anecdotal. Observation and Hydration: Monitor for signs of worsening respiratory distress and ensure adequate hydration. This management strategy differs from epiglottitis primarily in the less aggressive approach to airway intervention and the specific treatments aimed at reducing subglottic swelling typical of croup.",
    },
  ],
};
