export const GravesDisease = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "Please describe this image",
      sample_answer: "This is a clinical photograph of a patient with a large anterior neck swelling. my differential diagnosis would encompass several categories, including: Neoplastic Causes: This category divides into benign and malignant neoplasms. Benign neoplasms include thyroid adenomas and cysts. Malignant neoplasms could be primary thyroid cancers (papillary, follicular, medullary, anaplastic) or metastatic disease to the thyroid gland. Goiters: This encompasses non-toxic goiter (NTG), which can be diffuse or multinodular, and toxic goiter such as Graves' disease or toxic multinodular goiter. Inflammatory Conditions: This could include thyroiditis, such as Hashimoto's thyroiditis or subacute (de Quervain's) thyroiditis, and infectious etiologies leading to abscess formation. Thyroid Enlargement due to Iodine Deficiency: Although less common in iodine-sufficient regions, it's still a possibility, especially in at-risk populations. Cystic Lesions: Including thyroglossal duct cysts, which typically present along the midline of the neck. Inflammatory Conditions of Adjacent Structures: This might include lymphadenopathy secondary to infections or malignancies, or inflammatory enlargement of salivary glands.",
    },
    {
      question: "What would you inquire about during your history taking for this patient?",
      sample_answer: "In taking a history for a patient with an anterior neck lump, I would categorize my inquiries as follows: Symptoms Related to Thyroid Function: I'd ask about signs of hyperthyroidism (such as weight loss despite an increased appetite, heat intolerance, increased sweating, palpitations, and anxiety) and hypothyroidism (such as weight gain, cold intolerance, constipation, dry skin, and fatigue). This helps assess for thyroid dysfunction which could point towards Graves' disease, thyroiditis, or a functional thyroid nodule. Goiter Symptoms: Questions would focus on the duration and growth rate of the neck swelling, any associated pain (suggestive of thyroiditis or hemorrhage into a cyst/nodule), and compressive symptoms like difficulty swallowing, shortness of breath, or changes in voice. This can help distinguish between benign and malignant processes, and identify goiters that may be causing compressive symptoms. Ophthalmic Symptoms: Inquiring about eye symptoms such as grittiness, discomfort, visual changes, or the appearance of 'bulging eyes' could suggest thyroid eye disease associated with Graves' disease. Personal and Family History: I'd ask about personal or family history of thyroid disorders, radiation exposure (especially to the head, neck, or chest in childhood), and other autoimmune diseases, given the association with autoimmune thyroid disease. Systemic Symptoms: Questions would include recent infections, fever, or other systemic symptoms that could suggest an inflammatory or infectious process. Medication and Dietary History: Including use of medications like amiodarone or lithium, and dietary iodine intake, as these can affect thyroid function and size.",
    },
    {
      question: "What would you look for during your examination of this patient?",
      sample_answer: "During my examination of a patient with an anterior neck lump, my assessment would include: Inspection of the Neck: Observing the size, shape, and location of the lump. A diffusely enlarged thyroid could suggest a goiter, whereas a single nodule might indicate a thyroid adenoma or carcinoma. Palpation of the Thyroid: To assess the texture, size, mobility, and tenderness of the thyroid gland and any nodules. Hard, fixed nodules are more concerning for malignancy, while tenderness could suggest thyroiditis. Examination for Lymphadenopathy: Enlarged, firm, non-tender lymph nodes could indicate a malignancy. Assessment for Signs of Thyroid Dysfunction: Including tremor, overactive reflexes (hyperthyroidism), or delayed reflexes (hypothyroidism). Eye Examination: Looking for signs of thyroid eye disease such as exophthalmos, eyelid retraction, or limited eye movement. Evaluation for Compressive Symptoms: Checking for signs of tracheal compression (stridor, difficulty breathing) or esophageal compression (difficulty swallowing), as well as looking for pemberton's sign and general facial plethora.",
    },
    {
      question: "The patient is sweaty, with palpitations and anxiety. They have a large anterior neck swelling. What investigations would you undertake for this patient?",
      sample_answer: "Given the symptoms suggestive of hyperthyroidism and the presence of a large anterior neck swelling, I would conduct the following investigations: Thyroid Function Tests (TFTs): To measure TSH, Free T4, and Free T3 levels. I expect to find suppressed TSH and elevated Free T4 and Free T3 in hyperthyroidism. Thyroid Stimulating Immunoglobulins (TSIs) inluding anti-TSH, Anti-TPO and Anti-Tg: Positive TSIs would support a diagnosis of Graves' disease, indicated by the hyperthyroid symptoms and goiter. Ultrasound of the Thyroid: To evaluate the anatomy of the thyroid gland, distinguish between solid and cystic nodules, and identify characteristics suggestive of malignancy. In Graves' disease, there may be a diffuse increase in gland vascularity (thyroid inferno). Radioactive Iodine Uptake Test: To differentiate between Graves' disease (diffusely high uptake) and other causes of hyperthyroidism like thyroiditis (low uptake). Ophthalmological Assessment: If thyroid eye disease is suspected based on clinical examination. Fine Needle Aspiration Cytology (FNAC): For any suspicious nodules identified on ultrasound, to rule out thyroid carcinoma.",
    },
    {
      question: "The patient has a low TSH and positive anti-TSH antibodies. What is your diagnosis?",
      sample_answer: "My diagnosis would be Grave's disease. Graves' disease is an autoimmune disorder characterized by the production of thyroid-stimulating immunoglobulins (TSIs) that bind to and activate the thyroid-stimulating hormone (TSH) receptors on thyroid cells, leading to diffuse thyroid enlargement (goiter) and overproduction of thyroid hormones (hyperthyroidism). It is the most common cause of hyperthyroidism and can also lead to thyroid eye disease (ophthalmopathy) and, less commonly, a dermopathy known as pretibial myxedema. Graves' disease tends to run in families and is more common in women than in men.",
    },
    {
      question: "How would you treat this patient?",
      sample_answer: "I take a stepwise approach to management: Step 1: Initiate Antithyroid drugs. Carbimazole would be my first choice due to its once-daily dosing and lower incidence of severe side effects compared to Propylthiouracil (PTU). The exception would be in the first trimester of pregnancy or in cases of carbimazole intolerance, where PTU would be preferred. The patient would be on a 'block and replace' regimen or a titration regimen for 12-18 months. The 'block and replace' regimen involves blocking thyroid hormone synthesis with ATDs and replacing thyroid hormone with levothyroxine, whereas the titration regimen adjusts the dose of ATDs to maintain euthyroidism. Step 2: Evaluate for Remission: After 12-18 months, ATDs would be tapered off to assess for remission, defined as maintaining normal thyroid function off medication. If remission is achieved, the patient would still require long-term follow-up with periodic TFTs, as the risk of recurrence is significant, especially within the first year after stopping ATDs. Recurrence or Failure to Achieve Remission can be managed with Radioactive Iodine (RAI) Therapy or surgery. I would discuss the potential risks and benefits, including the likelihood of developing hypothyroidism post-treatment, which would necessitate lifelong thyroid hormone replacement. The patient may need a short course of ATDs to normalize thyroid function before RAI to minimize the risk of thyroid storm. Post-RAI: Monitoring TFTs at regular intervals post-RAI to detect and manage hypothyroidism. Surgery as Total Thyroidectomy is Preferred if the patient has a large goiter causing compressive symptoms, if there is suspicion of thyroid malignancy, or patient preference after discussing the risks and benefits. Preoperative preparation involves Achieving euthyroidism with ATDs, possibly supplemented with beta-blockers to control symptoms. In some cases, Lugol's iodine may be used shortly before surgery to decrease vascularity of the thyroid gland.",
    },
    {
      question: "What is a thyroid storm and how do you treat it?",
      sample_answer: "A thyroid storm is a life-threatening exacerbation of hyperthyroidism characterized by extreme symptoms of thyroid overactivity, such as high fever, severe tachycardia, agitation, delirium, nausea, vomiting, and potentially heart failure. It is often triggered by stress, infection, surgery, or untreated or inadequately treated hyperthyroidism. Treatment involves a multidisciplinary approach and includes: Supportive Care: Intensive care unit monitoring, cooling measures, fluid and electrolyte replacement. Antithyroid Medications: Such as Propylthiouracil (PTU) followed by iodine solution to inhibit thyroid hormone synthesis and release. Beta-Blockers: To control heart rate and blood pressure. Steroids: To reduce inflammation and possibly inhibit peripheral conversion of T4 to T3. Management of Triggering Factors: Such as antibiotics for infections. Preparation for Urgent Thyroidectomy: Once the patient is stabilized medically, in some cases.",
    },
    {
      question: "Tell me about this patient's eyes.",
      sample_answer: "This is a clinical photograph showing a patient with significant proptosis and lid lag. In the context of our patient, this would be characteristic of thyroid eye disease. Thyroid eye disease (TED), also known as Graves' ophthalmopathy, is an autoimmune inflammatory disorder associated with Graves' disease, where immune cells attack the muscles and other tissues around the eyes. This can lead to symptoms such as bulging eyes (exophthalmos), dry and gritty eyes, swelling of the eyelids, double vision (diplopia), and in severe cases, vision loss due to optic nerve compression.",
    },
    {
      question: "How would you manage the patient's thyroid eye disease?",
      sample_answer: "Management of thyroid eye disease is done in an MDT setting and involves: For Mild Cases: Lubricating eye drops, selenium supplements, and wearing sunglasses to protect the eyes from UV and wind. Elevating the head while sleeping can help reduce eyelid swelling. Moderate to Severe Cases: Corticosteroids to reduce inflammation, either orally or through intravenous administration. Immunosuppressive therapy for patients not responding to steroids. Surgical Intervention: In cases where there is no improvement with medical management or to address complications. Surgery may involve orbital decompression to relieve pressure on the optic nerve, strabismus surgery to correct double vision, or eyelid surgery to improve closure and appearance. Smoking Cessation: Smoking is a known risk factor for the development and worsening of thyroid eye disease.",
    },
    {
      question: "The thyroid is very large and your CT shows it is retrosternal. What factors would influence whether you need to do a sternotomy to remove it or not?",
      sample_answer: "The main factors are: Whether the majority of the thyroid is in the neck or in the chest And whethere it extends below the aortic arch or into the mediastinum. If the majority is in the chest or it goes below the aortic arch or into the mediastinum, it is prudent to involve cardiothoracic surgeons for a sternotomy approach.",
    },
    {
      question: "What would you tell a patient undergoing total thyroidectomy for Graves' disease during the consent process?",
      sample_answer: "During the consent process for a total thyroidectomy for Graves' disease, I would discuss the following points: Benefits: Definitive Treatment: Total thyroidectomy offers a permanent solution to hyperthyroidism in Graves' disease, especially in cases where medical management has failed or is not suitable. Relief of Symptoms: Surgical removal of the thyroid can relieve symptoms of hyperthyroidism and reduce the risk of thyroid storm. Improvement in Thyroid Eye Disease: Some studies suggest that thyroidectomy can lead to an improvement in thyroid eye disease symptoms. Risks: Hypothyroidism: Total thyroidectomy results in the complete removal of thyroid function, necessitating lifelong thyroid hormone replacement therapy. Recurrent Laryngeal Nerve Injury: There is a risk of injury to the recurrent laryngeal nerve. 5% temporary, 1% permanent. This can be unilateral, leading to voice changes or bilateral, requiring tracheostomy. Superior laryngeal nerve injury leading to voice fatigue and difficulty reaching high pitches. Hypoparathyroidism: Accidental removal or damage to the parathyroid glands can lead to transiently low calcium levels in 10% of patients, requiring calcium and vitamin D supplementation, with 1% having hypothyroidism potentially for life. Bleeding risk leading to haematoma and airway compromise requiring a return to theatre. Surgical Risks: As with any surgery, there are risks of pain, scar, infection, and adverse reactions to anesthesia.",
    },
    {
      question: "Where would you look for the right recurrent laryngeal nerve in your surgery?",
      sample_answer: "The Right Recurrent Laryngeal Nerve Originates from the vagus nerve and loops around the subclavian artery. It enters the neck more laterally and its path is less predictable than the left RLN. It typically ascends in the tracheoesophageal groove towards the larynx. It can be identified intraoperatively by tracing the nerve in the tracheoesophageal groove or by locating it near the inferior thyroid artery (ITA), where it may pass anteriorly, posteriorly, or between branches of the ITA. The right RLN's relationship with the thyroid gland is variable and can be found in close proximity to the ligament of Berry and the tubercle of Zuckerkandl, which can serve as landmarks for identification. Of note, a Non-Recurrent Laryngeal Nerve Occurs in about 0.6% of patients, almost exclusively on the right side. It does not loop around the subclavian artery but branches directly from the vagus nerve higher in the neck, passing directly to the larynx. This anomaly is associated with a retro-esophageal subclavian artery. Identifying a non-recurrent laryngeal nerve requires vigilance for any anatomical deviations, especially on the right side.",
    },
    {
      question: "Where would you look for the left recurrent laryngeal nerve in your surgery?",
      sample_answer: "Left Recurrent Laryngeal Nerve Originates from the vagus nerve and loops around the aortic arch. It has a more predictable path compared to the right RLN, ascending medially and superiorly in the tracheoesophageal groove to the larynx. Similar to the right, the left RLN can be identified by locating it in the tracheoesophageal groove or near the ITA. The left RLN commonly crosses behind the branches of the ITA, and its identification may also be aided by landmarks such as the ligament of Berry and the tubercle of Zuckerkandl.",
    },
    {
      question: "What are the postoperative considerations after total thyroidectomy?",
      sample_answer: "In the immediate post op period we observe for haematoma and airway compromise, being ready to return to theatre for evacuation of the haematoma should it be necessary. It is important to monitor for calcium homeostasis via clinical assessment and blood tests, to pick up and treat hypocalcaemia. This condition is typically addressed with oral calcium carbonate, dosed at 1-2 grams three to four times daily, and Calcitriol, the active form of Vitamin D, at 0.25-0.5 mcg twice daily to help with calcium absorption. Since the thyroid gland has been removed, lifelong thyroid hormone replacement therapy with levothyroxine is necessary. The starting dose is often based on the patient's weight, approximately 1.6 mcg/kg per day, adjusting based on Thyroid-Stimulating Hormone (TSH) levels to maintain them within the target range.",
    },
    {
      question: "Tell me about the thyroid hormones",
      sample_answer: "The thyroid gland produces two main hormones: Thyroxine (T4) and Triiodothyronine (T3). These hormones play a crucial role in regulating metabolism, energy generation, and the function of many systems in the body. T4 is the predominant form secreted by the thyroid gland but is converted into the more active T3 form in peripheral tissues. The production of these hormones is regulated by the Thyroid Stimulating Hormone (TSH), which is secreted by the pituitary gland in response to signals from the hypothalamus (TRH). These hormones influence growth, development, and various metabolic processes throughout the body.",
    },
    {
      question: "tell me about the important triangles in thyroid surgery.",
      sample_answer: "I am aware of Beah's triange, Simon's triangle and Joll's triangle. Beahrs Triangle is located posterior to the thyroid gland and becomes visible after retracting the ipsilateral thyroid medially. It is defined by: The Common Carotid Artery at the base, Inferior Thyroid Artery superiorly and the Recurrent Laryngeal Nerve anteriorly. Simon's triangle is also useful in locating the RLN, and is bounded by the trachea or oesophagus medially, the common carotid artery laterally and the inferior thyroid artery inferiorly. The RLN is typically found within this triangle. Joll's triangle is focused on the external brnach of the superior laryngeal nerve. The boundaries of Joll's Triangle are: Superiorly: the superior attachment of the strap muscles to the thyroid cartilage. Medially: the midline of the neck. Laterally: the upper pole of the thyroid gland and the superior thyroid vessels (the superior thyroid artery and vein). The superior thyroid artery is of particular interest as the EBSLN often runs close to it or within its branches as it approaches the larynx.",
    },
  ],
};
