export const Haemangioma = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "What is your differential diagnosis for this lesion?",
      sample_answer: "My differential diagnosis for this lesion on the scalp includes: Vascular Tumors: Infantile hemangioma (most likely given the description) Congenital hemangioma, including rapidly involuting congenital hemangioma (RICH) and noninvoluting congenital hemangioma (NICH) Vascular Malformations: Capillary malformation such as port wine stain Venous malformation Lymphatic malformation Non-Vascular Lesions: Dermoid cyst Sebaceous cyst Lipoma Infectious/Inflammatory Conditions: Abscess Fungal infection",
    },
    {
      question: "How are vascular anomalies classified?",
      sample_answer: "Vascular anomalies are classified by the International Society for the Study of Vascular Anomalies (ISSVA) into two main categories: Vascular Tumors: This includes benign, locally aggressive or borderline, and malignant tumours. Vascular Malformations: These are further divided into simple and combined forms, affecting capillaries, lymphatics, veins, arteriovenous connections, and major named vessels.",
    },
    {
      question: "How are haemangiomas classified?",
      sample_answer: "Hemangiomas are classified based on their presentation at birth and growth pattern into two main types: Infantile Hemangiomas: These are not usually present at birth or may appear as a faint red mark. They undergo a rapid proliferative growth phase in the first months of life, followed by a slow involution phase where the hemangioma gradually regresses. Infantile hemangiomas express GLUT-1 protein. Congenital Hemangiomas: These are fully formed at birth and do not express the GLUT-1 protein. They are further classified into: Rapidly Involuting Congenital Hemangioma (RICH): These regress completely within the first year of life. Noninvoluting Congenital Hemangioma (NICH): These do not regress and remain stable in size. Partially Involuting Congenital Hemangioma (PICH): These exhibit some degree of involution but do not regress completely.",
    },
    {
      question: "What are the phases of capillary haemangioma growth?",
      sample_answer: "Capillary hemangiomas, primarily infantile hemangiomas, undergo distinct phases: Proliferative Phase: This occurs during the first few months of life, where the hemangioma undergoes rapid growth. The most significant growth typically occurs between 5.5 to 7.5 weeks of age. Plateau Phase: Following the proliferative phase, the hemangioma's growth stabilizes. This phase lasts until about one year of age. Involution Phase: The hemangioma then gradually regresses. The rates of regression are as follows: 50% of hemangiomas regress by the age of 5 years. 70% by 7 years. Up to 80% by 9 years. Some hemangiomas may leave residual skin changes after involution, including fibrofatty tissue, excess skin, or discoloration.",
    },
    {
      question: "When assessing a child with a capillary haemangioma in the head and neck region, what are the important factors to elicit on your history and examination?",
      sample_answer: "When assessing a child with a capillary hemangioma in the head and neck region, important factors to elicit include: On History: Age of onset and presence of any herald patches at birth to suggest congenital origin. Progression in size and any rapid growth phases. Airway symptoms such as stridor, which could suggest subglottic involvement, especially in hemangiomas in the 'beard' distribution. Pain, ulceration, or skin changes over the hemangioma. Any family history of vascular anomalies or related syndromes. On Examination: Location, size, and type (superficial, deep, or compound) of the hemangioma. Presence of any pain, ulceration, or skin changes. Assessment for other cutaneous lesions in the head, neck, or torso which could indicate a syndrome or multiple hemangiomas. Examination for signs of airway compromise, including stridor or difficulty breathing. Assessment of the proximity to critical structures such as the eye, which could affect vision, or areas affecting feeding and breathing.",
    },
    {
      question: "Discuss the management options for a facial capillary hemangioma in a pediatric patient",
      sample_answer: "Management options for a facial capillary hemangioma in a pediatric patient include: Observation: Many facial capillary hemangiomas undergo spontaneous involution. Observation is appropriate for asymptomatic lesions without functional impairment or cosmetic concern. Medical Treatment: Propranolol: First-line therapy for infantile hemangiomas causing functional impairment or rapid growth. It helps reduce the size and redness of the hemangioma. Corticosteroids: Used in cases where propranolol is contraindicated or not effective. Surgical Options: Pulsed-Dye Laser Therapy: Effective for superficial lesions to lighten the hemangioma. Excision: Considered for hemangiomas that cause functional issues or do not respond to medical management. Ideal timing and approach depend on the hemangioma's size, location, and impact on the child. Other Treatments: Interferon alpha and Vincristine: Reserved for hemangiomas unresponsive to first-line treatments, especially those threatening life or function.",
    },
    {
      question: "When considering surgical intervention for a facial capillary hemangioma, what factors determine the timing and type of surgery?",
      sample_answer: "Factors determining the timing and type of surgery for a facial capillary hemangioma include: Size and Location: Larger hemangiomas or those in cosmetically sensitive areas may warrant earlier intervention. Proximity to vital structures (e.g., eyes, nose, mouth) necessitates careful planning. Response to Medical Treatment: Hemangiomas not responding to medical management (e.g., propranolol) may require surgical evaluation. Age and Health of the Child: Younger children may not tolerate certain treatments as well as older children. Overall health and readiness for surgery are considered. Potential for Functional Impairment: Hemangiomas causing or at risk of causing functional impairments (e.g., vision obstruction, breathing difficulties) may require more urgent intervention. Cosmetic Considerations: Significant disfigurement may prompt consideration for earlier surgical intervention to minimize psychosocial impact. Risk of Complications: Increased risk of ulceration or bleeding in the hemangioma may necessitate surgical intervention. The type of surgery (e.g., laser therapy, excision) is chosen based on the hemangioma's characteristics and the goal of treatment (e.g., cosmetic improvement, functional restoration).",
    },
    {
      question: "This child presents to you in respiratory distress, how would you manage them?",
      sample_answer: "I would suspect that they also have a subglottic haemangioma, which is present in 1% of those with cutaneous lesions but 50% of subglottic lesions are associate with cutaneous lesions. I would therefore manage the patient according to the APLS algorithm, doing an A-E approach with appropriate assessment and intervention at each phase. The child may ultimately need to have their airway secured with intubation or tracheostomy, ahead of diagnostic assessment with Microlaryngoscopy and Bronchoscopy.",
    },
    {
      question: "How do you perform the MLB/LTB for diagnosis?",
      sample_answer: "Having made a clear plan with our paediatric anaesthetics consultant and team, the child is placed under general anesthesia, maintaining spontaneous ventilation. Total intravenous anesthesia is preferred to minimize exposure to inhalant anesthetic gases. We would oxygenate the child with an facemask or ET tube used as a nasopharyngeal airway. An LMA is an alternative. This can be removed by the anesthesiologist once the patient achieves adequate anesthesia depth, and allowing us to place a laryngeal suspension laryngoscope once we have the patient in a supine position with an appropriate tooth guard in place. If not using TIVA, we would maintain the nasopharyngeal tube in situ to deliver the sevoflurane for anaesthesia. I would initially perform an oral cavity exaination, including palpating the palate, before passing my laryngoscope to the right side of the oral cavity and sweeping the tongue to the left to facilitate laryngoscopy. Once in, I connect the insufflation circuit to the laryngoscopy and proceed to spray topical 1% lidocaine to the vocal cords. I then use A 0-degree Hopkins rod telescope is then used to examine the airway structures systematically, from the soft palate and tonsils down to the lower trachea and main bronchi. I take Standardized photos of key airway structures, including the supraglottis, glottis, subglottis, and upper and lower trachea. My examination extends to the Carina, left main bronchus, and right main bronchus. I then suspend the laryngoscope with a chest support to stabilize it, facilitating detailed examination and manipulation. In particular, I use a right angled proble to palpate the larynx for abnormalities such as laryngeal cleft, and then assess for cricoarytenoid joint fixation. I can also size the airway with ET tubes, using positive pressure testing to assess for appropriate airway seal. After full examination, I carefully remove the endoscope and, check the ET tube depth to ensure proper placement.",
    },
    {
      question: "This is what you see at MLB, how would you approach the treatment, and what considerations would influence your choice of treatment?",
      sample_answer: "This is a subglottic haemangioma, my treatment approach for a subglottic hemangioma includes: Propranolol: This is First-line therapy due to its efficacy in reducing hemangioma size and mitigating symptoms. The dosing starts at 1 mg/kg/day in divided doses, potentially increasing up to 3 mg/kg/day based on response and tolerance. Steroids: Systemic corticosteroids may be considered if propranolol is contraindicated or if there is an inadequate response. Their use is less favored due to side effects. Surgical Options: For hemangiomas unresponsive to medical therapy or causing severe airway obstruction, surgical options include laser therapy for size reduction or surgical resection in severe cases. Airway Management: In cases of acute respiratory distress, securing the airway through intubation or tracheostomy may be necessary while long-term treatments take effect. Considerations influencing treatment choice include: The severity of airway obstruction and symptoms. Response to initial medical therapy. Potential side effects of medical treatments. Age and overall health of the child. Presence of other airway anomalies or systemic involvement. The goal is to relieve airway obstruction while minimizing treatment-related side effects and complications.",
    },
    {
      question: "What are the surgical approaches for treating a subglottic haemangioma?",
      sample_answer: "Surgical approaches for treating a subglottic hemangioma include Endoscopic and Open approaches. Endoscopic Laser Therapy: Utilizing a CO2 or Nd:YAG laser to precisely ablate the hemangioma, reducing its size and relieving airway obstruction. This minimally invasive approach is preferred for accessible lesions with minimal surrounding tissue damage. Microdebrider Excision: Endoscopic removal of the hemangioma using a microdebrider, which allows for precise cutting and suctioning of the lesion. This technique is suitable for larger or more complex lesions. Open Surgical Excision: In cases where the hemangioma is extensive or not amenable to endoscopic techniques, an open approach via laryngofissure may be necessary to completely excise the lesion. Tracheostomy: As a temporary measure in severe cases where immediate airway stabilization is needed and other treatments are being planned or have failed to relieve obstruction. The choice of surgical approach depends on the size, location, and extent of the hemangioma, as well as the child's overall health and presence of other airway anomalies.",
    },
    {
      question: "How does propranolol work in haemangiomas?",
      sample_answer: "Propranolol is a non-selective beta-blocker used as first-line treatment for infantile hemangiomas. It works by causing vasoconstriction, decreasing angiogenesis through downregulatingvascular endothelial growth factor (VEGF) and basic fibroblast growth factor (bFGF), and inducing apoptosis in hemangioma cells. In patients who have been appropriately assessed for contraindications such as asthma and cardiac conditions, dosing starts at 1mg/kg/day in divided doses which increase to 2-3mg/kg/day based on response and tolerance. We would expect reduction in colour and size within the first few weeks. We also monitor for side effects such as hypoglycaemia, bradycardia and bronchospasm. regular follow ups are required to adjust the dose and monitor for side effects.",
    },
    {
      question: "What are the syndromes associated with haemangiomas?",
      sample_answer: "Hemangiomas, particularly when presenting in specific patterns or locations, can be associated with various syndromes, underscoring the importance of a comprehensive evaluation. The key syndromes associated with hemangiomas include: PHACES Syndrome: Characterized by Posterior fossa brain anomalies, Hemangiomas of the face that are typically large and segmental, Arterial anomalies, Cardiac defects, Eye abnormalities, and occasionally Sternal defects or Supraumbilical raphe. It is most commonly associated with large facial hemangiomas. LUMBAR/SACRAL Syndrome: Associated with lower body segmental hemangiomas and may include anomalies such as Spinal dysraphism, Urogenital anomalies, Myelopathy, Bony deformities, Anorectal malformations, Arterial anomalies, and Renal anomalies. The presence of a large segmental hemangioma in the lumbosacral area warrants evaluation for these associated conditions.",
    },
  ],
};
