export const HHT = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "Please describe this picture",
      sample_answer: "This is a clinical photograph of a patient with multiple tongue and lip telangiectasia.",
    },
    {
      question: "What is your differential diagnosis for this patient?",
      sample_answer: "My differential diagnoses would include: Hereditary Hemorrhagic Telangiectasia (HHT): Most likely diagnosis given the specific presentation of mucocutaneous telangiectasia. Scleroderma: Can also present with telangiectasia, typically accompanied by skin thickening and tightening. Cushing's Syndrome: Can manifest with telangiectasia due to corticosteroid excess. Liver Disease: Chronic liver disease can lead to telangiectasia due to hormonal imbalances and vascular changes. Rosacea: Primarily affects the facial skin and can present with telangiectasia, but it typically involves more erythema and flushing.",
    },
    {
      question: "Would you ask during your history for this patient?",
      sample_answer: "I would inquire about Bleeding History, focusing on the frequency, duration, and severity of any nosebleeds, as recurrent spontaneous epistaxis is a hallmark of HHT. Family History: Asking about similar symptoms in family members to assess for a genetic pattern indicative of HHT. Other Symptoms of AVMs: Questions about signs of gastrointestinal bleeding, such as black stools or hematemesis, and any history of hemoptysis or neurological symptoms like seizures or headaches to detect other AVMs. Medication Use: Clarifying use of medications like anticoagulants or NSAIDs that could exacerbate bleeding. Impact on Daily Life: Understanding how these symptoms affect their daily activities or quality of life to gauge the severity and guide management strategies.",
    },
    {
      question: "What would you look for during your examination of this patient?",
      sample_answer: "Mucocutaneous Telangiectasia: I would conduct a thorough examination of the skin and mucous surfaces, looking for the presence of telangiectasia, especially in typical areas like the lips, tongue, fingers, and nasal mucosa. Signs of Chronic Blood Loss: Checking for signs of anemia such as pallor and tachycardia, and evaluating for any active bleeding sites. Systemic Signs: Assessing for signs of liver disease (jaundice, hepatomegaly) or heart failure (edema, elevated jugular venous pulse) which could be related to AVMs in these organs. Neurological Examination: A neurological examination if there are reported neurological symptoms to rule out intracranial AVMs or hemorrhages.",
    },
    {
      question: "What investigations would you undertake for this patient?",
      sample_answer: "The investigative approach would be multifaceted, aiming to confirm the diagnosis and assess the extent of organ involvement: Blood Tests: Complete blood count, iron studies, and coagulation profile to assess for anemia and other hematological abnormalities. Imaging Studies: High-resolution CT and MRI scans of the chest, abdomen, and pelvis to evaluate for arteriovenous malformations in the lungs, liver, and other organs. Brain MRI or CT could be considered if there are any neurological symptoms. Endoscopic Evaluations: Gastroscopy or colonoscopy if there is evidence of gastrointestinal bleeding. Genetic Testing: While not always necessary for diagnosis, genetic testing for mutations known to cause HHT (ENG, ACVRL1, MADH4) could be informative, particularly for family planning or confirming the diagnosis in ambiguous cases.",
    },
    {
      question: "What is hereditary haemorrhagic telangiectasia?",
      sample_answer: "Hereditary haemorrhagic telangiectasia (HHT), also known as Osler-Weber-Rendu Syndrome, is an autosomal dominant vascular disorder. It is characterized by recurrent epistaxis, mucocutaneous telangiectasias (particularly on the lips, tongue, and nasal cavity), and arteriovenous malformations (AVMs) in internal organs such as the lungs, liver, and brain. The disease typically manifests in adolescence or early adulthood but can present at any age, depending on the severity and extent of vascular involvement. The diagnosis is clinical, based on family history and the presence of characteristic signs, and can be confirmed using genetic testing.",
    },
    {
      question: "How is hereditary haemorrhagic telangiectasia diagnosed?",
      sample_answer: "The diagnosis of HHT is primarily based on the Curaçao criteria, which includes: Spontaneous, recurrent epistaxis. Multiple telangiectasias, especially at characteristic sites such as the lips, oral cavity, fingers, and nose. Proven visceral AVMs (e.g., in lungs, liver, brain). A first-degree family member with HHT. Having three or four of these criteria confirms a definite diagnosis of HHT, while two criteria indicate a possible diagnosis. This clinical diagnostic method allows for early identification and management of the disease and its complications.",
    },
    {
      question: "What is the pathophysiology of hereditary haemorrhagic telangiectasia?",
      sample_answer: "HHT is characterized by a genetic defect in the signaling pathway of transforming growth factor-beta (TGF-?), which plays a crucial role in vascular development and repair. The mutations in genes like ENG, ACVRL1, and MADH4 lead to abnormalities in the structure and function of the blood vessels. The vessels become fragile, leading to the formation of telangiectasias and AVMs. These abnormal blood vessels are prone to rupture, resulting in bleeding and other complications. The lack of normal vascular smooth muscle cells and elastic fibers in the vessel walls further contributes to their fragility and the clinical manifestations of the disease.",
    },
    {
      question: "What are the systemic effects of hereditary haemorrhagic telangiectasia?",
      sample_answer: "The systemic effects of HHT are widespread and can affect multiple organ systems: Epistaxis and GI Bleeding: Recurrent nosebleeds are the most common symptom, and gastrointestinal bleeding is also frequent, which can lead to iron-deficiency anemia and require iron supplementation or blood transfusions. Pulmonary AVMs: These can result in hypoxemia, hemoptysis, and right-to-left shunts, potentially leading to paradoxical emboli and stroke. Hepatic AVMs: These can cause high-output cardiac failure and portal hypertension. Neurological Complications: Brain AVMs may lead to seizures, migraines, and hemorrhagic strokes. Cardiac Overload: High-output heart failure can occur due to the increased blood flow through AVMs.",
    },
    {
      question: "What is the genetics of HHT?",
      sample_answer: "HHT is an autosomal dominant disorder primarily caused by mutations in the ENG and ACVRL1 genes, which are involved in the TGF-? signaling pathway. These mutations account for the majority of cases. Another less common gene involved is MADH4, which is also associated with juvenile polyposis syndrome. Genetic testing can identify these mutations, confirming the diagnosis and helping with family counseling and management strategies.",
    },
    {
      question: "How would you manage a patient with HHT?",
      sample_answer: "Managing a patient with HHT requires a coordinated approach involving multiple specialties: Multidisciplinary Team (MDT) Involvement: Collaboration with a geneticist, hematologist, and other specialists (e.g., gastroenterologist, pulmonologist) is essential. Conservative Measures: Management includes nasal emollients, humidification, and avoiding activities or medications that could provoke bleeding. Medical Treatments: Iron supplementation, tranexamic acid to reduce bleeding episodes, and hormonal therapies such as tamoxifen or oestrogen-based therapies. Anti-angiogenic agents like bevacizumab may be used in severe cases. Surgical Interventions: Options include laser therapy (e.g., KTP laser) to ablate telangiectasias, similarly coblation to ablate telangiectasia, septodermoplasty to replace telangiectatic mucosa with grafts, and procedures like Youngs procedure to reduce nasal airflow and dryness that can lead to epistaxis.",
    },
    {
      question: "Tell me more about the medical treatments for HHT",
      sample_answer: "The 2020 guidelines recommend a range of medical treatments for HHT, focusing on controlling bleeding and managing anemia: Iron Supplementation: To manage iron deficiency anemia, oral or intravenous iron supplements are prescribed, often in conjunction with local or systemic treatments to control bleeding. Tranexamic Acid: For patients with frequent or severe epistaxis, oral tranexamic acid is recommended as it helps reduce the duration and frequency of bleeding episodes. Systemic Antiangiogenic Therapy: Bevacizumab is specifically recommended for severe cases of HHT where there is significant bleeding that is not controlled by local treatments. This therapy has shown efficacy in reducing bleeding episodes and the need for blood transfusions. Bevacizumab treatment involves an induction phase of six infusions followed by maintenance therapy, which may vary in frequency depending on the patients response. Other Therapies: The guidelines note the use of tamoxifen as an alternative systemic therapy, particularly when bleeding is difficult to control with other measures. Although not as prominently recommended as bevacizumab, tamoxifen has been used effectively in some HHT patients.",
    },
    {
      question: "What are the surgical options for HHT as per the latest guidelines?",
      sample_answer: "Surgical and Procedural Treatments for HHT include: Laser Therapy and Cautery: These methods are often first-line treatments for nasal and gastrointestinal telangiectasias, though we try to avoid cautery. Laser therapy, such as KTP (potassium-titanyl-phosphate) laser, provides precision that minimizes damage to surrounding tissues, making it suitable for delicate areas like the nasal mucosa. Septodermoplasty involves removing diseased mucosa and replacing it with a graft, and is often used for patients with severe and recurrent epistaxis. It provides a long-term solution by replacing the fragile mucosal surface with more resilient tissue, potentially reducing the frequency of bleeding episodes. Young's Procedure involves the surgical closure of the nostrils to prevent airflow, which can dry and irritate the nasal passages, leading to bleeds. It is Reserved for the most severe cases where other therapies have been ineffective. Coblation Therapy is Utilized for severe nasal epistaxis that does not respond adequately to more conservative treatments or simpler surgical interventions. It Operates at lower temperatures to precisely ablate the target tissue without extensive damage to surrounding areas, reducing recovery time and risk of additional bleeding. Silicone Splints are employed postoperatively after nasal surgeries or as an independent measure to support the nasal structure and reduce bleeding by stabilizing the nasal mucosa and preventing contact with airflow that can dry and crack the delicate tissues. They help maintain the integrity of the nasal passages during the healing process, reduce bleeding frequency, and can be particularly useful in patients undergoing repeated procedures. Embolization is Employed primarily to treat larger arteriovenous malformations (AVMs), especially in the lungs and brain, to prevent severe complications like strokes or heart failure.",
    },
    {
      question: "How do you manage epistaxis related to HHT?",
      sample_answer: "My initial management focuses on patient education, preventative care and topical therapies. Educating patients on gentle nasal care, such as as avoiding nasal trauma, such as nose picking, and keeping the nasal cavity moist with saline sprays and humidifiers, especially in dry environments. Topical Therapies such as Moisturizing Ointments: To help maintain nasal mucosa hydration. Nasal Saline Sprays can help to keep the nasal passages moist and reduce the frequency of nosebleeds. Humidification, for example, Using room humidifiers, especially in dry climates or during winter months, to help prevent nasal drying. I add medical treatments in a stepwise manner, generally starting with oral tranexemic acid. I Where the patient is actively bleeding, I manage them using ATLS A to E principles of simultaneous assessment and resuscitation, including with blood transfusion if necessary. I use topical adrenaline and tranexamic acid with dissolvable packing such as nasopore, while seeking to avoid cautery and traumatic packing as much as possible, but I would consider them for refractory cases.",
    },
  ],
};
