export const LaryngealCancer = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "A 62 year old male presents to you with hoarseness. What is your differential diagnosis?",
      sample_answer: "I would categorize my differential diagnosis for a middle-aged patient presenting with hoarseness into several groups: Infectious: Acute laryngitis, fungal laryngitis. Neoplastic: Squamous cell carcinoma of the larynx, papillomatosis, benign vocal cord nodules or polyps. Inflammatory: Chronic laryngitis, vocal cord granulomas. Neurological: Vocal cord paralysis or paresis. Traumatic: Vocal cord trauma from intubation or overuse. Functional: Muscle tension dysphonia.",
    },
    {
      question: "What would you inquire about during your history taking for this patient?",
      sample_answer: "I would ask about the following, categorized by their relevance: Symptoms Duration and Onset: Sudden onset might suggest trauma or infection, while a gradual onset might indicate a neoplasm or chronic inflammatory condition. Smoking History: Strongly associated with laryngeal squamous cell carcinoma. Alcohol Consumption: Increases the risk of laryngeal cancer. Voice Use: Overuse or misuse of the voice can lead to benign vocal cord lesions. Associated Symptoms: Weight loss and persistent pain might indicate a malignancy. Difficulty swallowing (dysphagia) and pain when swallowing (odynophagia) are particularly concerning for advanced disease. Referred otalgia could also be suggestive of more extensive disease due to shared sensory innervation. Past Medical History: Previous head and neck cancers or treatments could affect the larynx. Exposure to Irritants: Occupational exposure to irritants or voice use could contribute to laryngeal conditions and how they're managed.",
    },
    {
      question: "What would you look for during your examination of this patient?",
      sample_answer: "During my examination, I would categorize my findings as follows: General Inspection: Note any signs of cachexia or weight loss that may suggest malignancy. Oral Examination: Check for any lesions that might indicate a secondary primary tumor or spread of a primary laryngeal tumor. Neck Examination: Palpate for lymphadenopathy, which could indicate metastasis in the case of malignancy. Flexible Nasolaryngoscopy: Observe vocal cord mobility, any masses or lesions, and the state of the mucosa. Restricted vocal cord mobility could indicate tumor infiltration or nerve damage.",
    },
    {
      question: "This is what you see on flexible nasendoscopy. The vocal cords are moving symmetrically and the lesion does not extend elsewhere. How will you investigate this?",
      sample_answer: "This leads me to suspect that this is an early glottic tumour, such as a T1, however the involvement of the anterior commissure is concerning. Hence, I will perform a CT of the neck and thorax to assess for synchronous lung primary and extension through broyle's ligament. I will then perform a microlaryngoscopy and biopsy under general anaesthesia to allow for diagnosis.",
    },
    {
      question: "What is the significance of the lesion involving the anterior commissure?",
      sample_answer: "There is evidence to suggest that the anterior commisure is an area of weakness for cancer to spread deeper because Broyle's ligament penetrates the thyroid cartilage to allow tumour invasion as there is a lack of perichondrium or periosteum in the area of ligament insertion. The anterior commisure is also rich in fibrous tissue, making surgical intervention more complex and increasing the risk of recurrence. Lesions involving the anterior commissure also have a higher likelihood of crossing midline, affecting both vocal cords, which can complicate preservation of voice quality and necessitate more extensive treatment.",
    },
    {
      question: "Describe the T staging of a supraglottic cancer.",
      sample_answer: "For supraglottic cancer, the T staging is as follows: T1: Tumor limited to one subsite of the supraglottis with normal vocal cord mobility. T2: Tumor invades mucosa of more than one adjacent subsite of the supraglottis or an area outside the supraglottis without laryngeal fixation. T3: Tumor limited to the larynx with vocal cord fixation and/or invades the postcricoid area, pre-epiglottic tissues, paraglottic space, and/or minor thyroid cartilage erosion. T4a: Moderately advanced disease; tumor invades through the thyroid cartilage, and/or extends to tissues beyond the larynx (e.g., trachea, soft tissues of the neck). T4b: Very advanced disease; tumor invades prevertebral space, encases the carotid artery, or involves mediastinal structures.",
    },
    {
      question: "Describe the T staging of a glottic cancer.",
      sample_answer: "The T staging for glottic cancer is categorized as follows: T1: Tumor limited to the vocal cords with normal mobility. T1a: Limited to one vocal cord. T1b: Involves both vocal cords. T2: Tumor extends to the supraglottis and/or subglottis, or with impaired vocal cord mobility. T3: Tumor limited to the larynx with vocal cord fixation or invades the paraglottic space, or with minor thyroid cartilage erosion. T4a: Moderately advanced disease; tumor invades through the thyroid cartilage and/or extends to tissues beyond the larynx. T4b: Very advanced disease; tumor invades the prevertebral space, encases the carotid artery, or involves mediastinal structures.",
    },
    {
      question: "Describe the T staging of a subglottic cancer.",
      sample_answer: "For subglottic cancer, T staging is as follows: T1: Tumor limited to the subglottis. T2: Tumor extends to the vocal cord(s), with normal or impaired mobility. T3: Tumor limited to the larynx with vocal cord fixation. T4a: Tumor invades through the cricoid or thyroid cartilage, and/or extends to tissues beyond the larynx. T4b: Very advanced disease; tumor invades the prevertebral space, encases the carotid artery, or involves mediastinal structures. The Sunnybrook system, on the other hand, offers a more comprehensive evaluation by quantifying facial symmetry at rest, voluntary movement, and synkinesis. It provides scores in these categories, leading to a more detailed assessment of facial function. This system allows for a nuanced understanding of the patient's condition, which is particularly useful in managing and tracking recovery and the effectiveness of treatments over time.",
    },
    {
      question: "How would you manage this if it were a T2N0 glottic SCC?",
      sample_answer: "For a T2N0 glottic squamous cell carcinoma (SCC), management strategies aim at balancing oncologic control with preservation of voice and laryngeal function. Options include: Transoral Laser Microsurgery (TLM): Offers the benefit of precise tumor removal with minimal impact on surrounding tissues, suitable for lesions amenable to endoscopic resection. Radiotherapy: As a single modality can achieve good control rates while preserving the larynx's structure and function. My MDT would tend to prefer this for anterior commisure involving lesions. The choice between TLM and radiotherapy depends on the lesion's specifics, including its size and exact location, as well as patient preferences, particularly regarding potential impacts on voice quality.",
    },
    {
      question: "Tell me about the types of cordectomy, and advise which type you do for T1 and T2 glottic SCC.",
      sample_answer: "Cordectomy types vary based on the extent of resection: Type I (Subepithelial Cordectomy): Removal of the superficial layer of the vocal cord, suitable for very superficial lesions. Type II (Subligamentous Cordectomy): Involves resection up to the vocal ligament, used for lesions that extend deeper but do not involve the vocalis muscle. Type III (Transmuscular Cordectomy): Involves partial resection of the vocalis muscle, for lesions with deeper involvement. Type IV (Total Cordectomy): Complete resection of the vocal cord, for extensive T1 or some T2 lesions that occupy a significant portion of the vocal cord. Type V (Extended Cordectomy): Involves resection beyond the vocal cord to adjacent structures, such as contralateral cord (Va), arytenoids (Vb), ventricle (Vc), and subglottis (Vd). For T1 glottic SCC, Types I or II cordectomy might be sufficient, aiming for complete lesion resection while preserving as much normal tissue as possible. For T2 lesions, especially those with greater depth or volume, Types III or IV, or even Type V in certain situations, may be necessary to ensure complete removal while still attempting to maintain functional outcomes.",
    },
    {
      question: "How would you manage this if it were a T3N1 glottic SCC?",
      sample_answer: "For T3N1 glottic SCC, management would be more aggressive, given the more advanced local disease and nodal involvement. The primary options would include: Concurrent Chemoradiotherapy: This is often the preferred approach for laryngeal preservation, aiming to treat both the primary tumor and the nodal disease effectively. Total Laryngectomy with Neck Dissection, followed by postoperative radiotherapy or chemoradiotherapy, may be necessary for cases where laryngeal preservation is not feasible due to the extent of the disease or where function is already significantly compromised. Laryngeal function is critically relevant in these cases. The decision between a laryngeal preservation approach and total laryngectomy heavily depends on the existing function of the larynx (e.g., voice quality, airway patency, and swallowing function) and the expected outcomes post-treatment. Preserving laryngeal function is a priority, but not at the expense of oncologic control. Patient preference, expected quality of life, and the potential for rehabilitation post-treatment are also significant considerations in the management plan.",
    },
    {
      question: "How would you manage this if it were a T2N0 supraglottic SCC?",
      sample_answer: "For a T2N0 supraglottic squamous cell carcinoma (SCC), the goal is to achieve oncological control while preserving as much function and normal anatomy as possible. Management options include: Transoral Laser Microsurgery (TLM): This minimally invasive technique can be used for precise tumor removal, preserving surrounding healthy tissue and function. It's particularly useful for accessible lesions without extensive involvement. Radiotherapy: As a single modality, radiotherapy can effectively treat the primary tumor while sparing the surrounding structures, thus maintaining function. Partial Laryngectomy: In selected cases where the tumor's size or location might not be amenable to TLM, a more extensive surgical approach might be necessary. However, this would typically be reserved for cases where less invasive options are not feasible or have been unsuccessful.",
    },
    {
      question: "How would you manage this if it were a T4 glottic SCC?",
      sample_answer: "Management of a T4 glottic SCC involves treating a locally advanced cancer that has invaded through the thyroid cartilage or other nearby structures. Given the extent of the disease, treatment options include: Total Laryngectomy with Neck Dissection: This is often the primary treatment for T4 lesions due to the extent of local invasion. Removing the larynx and affected lymph nodes provides the best chance for oncologic control. Postoperative Radiotherapy or Chemoradiotherapy: Following surgery, additional treatment may be necessary to address microscopic residual disease and improve local control and survival rates. Chemoradiotherapy as a Primary Treatment: In selected cases, primarily based on patient preference or if surgery is not feasible due to other health conditions, concurrent chemoradiotherapy may be considered as a larynx-preservation approach. However, the efficacy may be limited by the tumor's extent and the potential for significant side effects.",
    },
    {
      question: "When in post operative radiotherapy used? When in chemoraddiotherapy used?",
      sample_answer: "Postoperative radiotherapy is recommended for: Close or positive surgical margins. Extracapsular spread of tumor in lymph nodes. Advanced primary tumor stages (T3 or T4). Perineural invasion. Lymphovascular invasion. Multiple lymph nodes involved with cancer. It targets microscopic disease left after surgery to reduce recurrence risk. Postoperative Chemoradiotherapy Postoperative chemoradiotherapy is used for: Positive surgical margins with a higher risk of residual disease. Extracapsular nodal extension, indicating a higher likelihood of metastatic spread. Numerous lymph nodes involved, suggesting advanced regional disease. Very advanced primary tumors (T4) with deep invasion into surrounding structures.",
    },
    {
      question: "Tell me about ongoing research trials in this field.",
      sample_answer: "'The Vocal-cord vs. Complete Laryngeal Radiotherapy for Early Glottic Cancer' (VOCAL) trial, assessing the non-inferiority of vocal-fold-only radiotherapy compared to complete larynx radiotherapy in T1N0 glottic laryngeal SCC, aiming to preserve voice quality while maintaining oncologic control. The RTOG 9512 Trial: This trial examined the efficacy of combining chemotherapy with radiation therapy in advanced laryngeal cancer. The goal was to see if this combination could improve survival rates while preserving the larynx. The DeLOS-II Trial: Investigating the role of induction chemotherapy followed by transoral laser microsurgery (TLM) in patients with laryngeal and hypopharyngeal cancers. The aim is to assess whether this approach can be a larynx-preserving alternative to total laryngectomy. VOICE Trial (Voice Outcome after Treatment for Early-stage Glottic Cancer): This study compares voice quality outcomes between patients undergoing transoral laser microsurgery and those receiving radiotherapy for early-stage glottic cancer. The trial seeks to understand which treatment modality offers better voice preservation. The LARCH Study (Laryngeal Cancer Cohort): An observational study aiming to collect comprehensive data on patients with newly diagnosed laryngeal cancer to identify factors influencing treatment outcomes and quality of life. The TROG 12.01 Trial (Trans Tasman Radiation Oncology Group): This trial looks into the feasibility and efficacy of using PET-CT guided radiotherapy in head and neck cancers, including laryngeal cancer, to improve targeting of radiation therapy and potentially reduce side effects. PembroRad Trial: A study examining the effectiveness of adding pembrolizumab, an immunotherapy drug, to standard radiation therapy for patients with advanced laryngeal squamous cell carcinoma. The goal is to see if this combination can improve disease control and survival.",
    },
  ],
};
