export const LymphaticMalformation = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "What is your differential diagnosis for this lesion?",
      sample_answer: "This is a clinical photograph showing a child with a large left sided neck swelling. My differential diagnosis would include congenital causes such as a lymphatic malformation, branchial cleft anomaly and vascular malformation. Acquired causes would break down into infectious causes such as deep neck space abscess or more superficial abscesses, including TB related, as well lymphadenitis. I would also consider neoplastic causes, such as benign ones like lipoma or malignant ones like lymphoma, rhabdomyosarcoma and metastatic disease. Inflammatory causes would include Kawasaki disease.",
    },
    {
      question: "How do you classify vascular malformations?",
      sample_answer: "Vascular malformations are classified based on the type of vascular flow and the vessels involved, which affects their clinical presentation and management strategies: High-Flow Malformations: Primarily arteriovenous malformations (AVMs) characterized by direct connections between arteries and veins without a capillary bed, leading to a high-flow state. They often present with a palpable thrill or audible bruit. Low-Flow Malformations: Include lymphatic, capillary, and venous malformations. Lymphatic Malformations (LM): Comprise macrocystic, microcystic, and mixed types. They present as soft, compressible masses, often with skin discoloration. Capillary Malformations: Known as port-wine stains, these are present at birth and typically do not regress. They can be associated with syndromes like Sturge-Weber. Venous Malformations: These are ectatic venous channels that can cause disfigurement, pain, and other complications. They are often blue, compressible, and may enlarge with Valsalva maneuver.",
    },
    {
      question: "Elaborate on the classification of lymphatic malformations.",
      sample_answer: "Lymphatic malformations (LMs) are classified based on the size and type of the lymphatic cysts that comprise the lesion. Macrocystic Lymphatic Malformations consist of large lymphatic cysts, each larger than 2 cm in diameter. They tend to be infrahyoid. Microcystic Lymphatic Malformations are Composed of small cysts less than 2 cm in diameter. They can infiltrate more diffusely into surrounding tissues, such as the tongue muscles, making them more challenging to treat. They tend to be suprahyoid. Mixed Lymphatic Malformations: Featuring both macrocystic and microcystic components. This was formaly called cystic hygroma and lymphangioma.",
    },
    {
      question: "Discuss the staging of lymphatic malformations.",
      sample_answer: "The Modified de Serres Staging for lymphatic malformations provides a framework for assessing the extent of the lesion, which can guide treatment and prognostication: Stages I to III: Focus on unilateral malformations with respect to the hyoid bone (infrahyoid, suprahyoid, or both). Stages IV to VI: Address bilateral malformations and their relation to the hyoid bone (Suprahyoid, both, and infrahyoid. Stage VII: Specifies retropharyngeal malformations, indicating a potential for airway obstruction. Stage M: Indicates mediastinal extension, which can have implications for respiratory function and may require intricate surgical management.",
    },
    {
      question: "What is the pathophysiology of a lymphatic malformation?",
      sample_answer: "The pathophysiology of lymphatic malformations (LMs) involves the abnormal development or obstruction of the primitive lymphatic system leading to irregular, cyst-like growths. These malformations are characterized by: Lymphoendothelial Hyperplasia: Excessive growth of the endothelial lining within the lymphatic vessels, contributing to the formation of the cystic structures. Absence of Normal Lymph Flow: Resulting from the malformed or obstructed lymphatic vessels, causing fluid to accumulate within the cysts. Histopathological Features: Include the presence of mature endothelium with normal mitotic figures, distinguishing them from vascular tumors which have increased mitosis.",
    },
    {
      question: "When assessing a child with a lymphatic malformation in the head and neck region, what are the important factors to elicit on your history and examination?",
      sample_answer: "When assessing a child with a lymphatic malformation in the head and neck region, important factors to consider include: Age of Onset and Growth Pattern: LMs are congenital, but the timing of presentation and growth rate can provide clues about the type and potential complications. Symptoms: Look for dysphagia, dyspnea, changes in voice, or signs of infection within the malformation, which could indicate acute exacerbation or complications. Physical Examination: Assess the location, size, consistency, and extent of the malformation. Palpate for any pulsation (to differentiate from arteriovenous malformations), auscultate for a bruit and examine the skin overlying the malformation for discoloration or vesicles. Airway Assessment: Given the potential for airway obstruction, assess for stridor, wheezing, or respiratory distress, and consider flexible nasopharyngoscopy if appropriate.",
    },
    {
      question: "How would you investigate this patient?",
      sample_answer: "Investigations for a patient with a lymphatic malformation should include: Imaging Studies: To define the extent and type of the malformation. MRI: The most informative for detailing the extent, contents (macro vs. microcystic), and relationship of the LM to surrounding structures. Expect to see fluid-filled cystic structures with varying sizes. Ultrasound, including doppler is Useful for distinguishing between macrocystic and microcystic lesions, characterising the flow and guiding sclerotherapy procedures. If a high flow lesion is identified, further assessment with MRA should be undertaken. Laboratory Tests: May include complete blood count and markers of infection if an acute exacerbation is suspected. Genetic and Syndromic Evaluation: If the malformation is part of a syndrome, genetic counseling and testing may be indicated.",
    },
    {
      question: "Your MRI confirms a mixed lymphatic malformation, how would you manage it?",
      sample_answer: "Management of a mixed lymphatic malformation would involve a multi-disciplinary approach focusing on minimizing symptoms and preventing complications. Options include Conservative measures to monitor asymptomatic lesions without active intervention unless necessary. It may include, compression garments, pain management and infection prevention. Medical treatments include Sclerotherapy, with Injection of sclerosing agents (e.g., OK-432, doxycycline or bleomycin) directly into the cystic spaces of the LM to reduce their size by causing inflammation and subsequent scarring. Sirolimus (Rapamycin): An mTOR inhibitor that has shown effectiveness in reducing the size of LMs by targeting the abnormal growth pathways involved in their development. It is especially useful for complex, diffuse, or surgically challenging LMs. Propranolol: Although more commonly used for infantile hemangiomas, propranolol has been reported to have some effect on reducing the growth of certain LMs. Surgery may be considered for LMs that cause significant symptoms, are located in areas where they affect function, are refractory to medical treatment or pose a risk for complications. The goal is often complete removal, though partial resection may be performed to preserve nearby structures and functions. CO2 Laser, Microdebrider or coblation can be Used for debulking and precise removal of LMs, especially in sensitive areas like the airway or tongue, minimizing damage to surrounding tissues.",
    },
    {
      question: "What complications would you be concerned about if left untreated?",
      sample_answer: "If left untreated, lymphatic malformations can lead to several complications: Infection and Inflammation: Can cause sudden enlargement of the malformation and pain. Spontaneous haemorrhage into macrocysts can occur too. Airway Obstruction: Particularly with head and neck LMs, leading to respiratory distress or difficulty swallowing. Disfigurement and Functional Impairment: Especially with visible locations or those that interfere with joint movement. Psychosocial Impact: Due to cosmetic appearance and potential for bullying or social isolation in children.",
    },
    {
      question: "You are consulted by the fetal maternal medicine team because they are concerned about a 35-week pregnant woman whose pregnancy they suspect has a cervicofacial mass. How do you think they will have determined this? and what would be your differential diagnosis?",
      sample_answer: "The fetal maternal medicine team likely determined the presence of a cervicofacial mass through prenatal ultrasound and MRI findings: Ultrasound Findings: May show a cystic or solid mass in the cervicofacial area, with or without evidence of polyhydramnios due to potential swallowing difficulties caused by the mass. MRI Findings: Provides more detailed information about the mass's size, location, and relationship to surrounding structures. A T2-hyperintense lesion suggests a cystic nature, commonly seen in lymphatic malformations. Differential Diagnosis: Includes lymphatic malformation, teratoma, hemangioma, and other congenital tumors or cysts (such as branchial cleft cysts).",
    },
    {
      question: "What is an EXIT procedure and what factors would lead you to plan one for this patient?",
      sample_answer: "The EXIT (Ex Utero Intrapartum Treatment) procedure is a specialized surgical delivery technique designed to ensure fetal stability and secure the airway while maintaining uteroplacental circulation. Factors leading to the planning of an EXIT procedure for this patient would include: Evidence of a Large Cervicofacial Mass: Potentially obstructing the airway and necessitating immediate intervention upon delivery. Risk of Airway Obstruction: Identified through prenatal imaging, indicating the fetus may not breathe independently at birth. Preparation for Immediate Intervention: Including the potential need for tracheostomy or resection of the mass to secure the airway.",
    },
    {
      question: "Describe the EXIT procedure.",
      sample_answer: "The EXIT procedure involves: Preparation: A multidisciplinary team including obstetricians, neonatologists, pediatric surgeons, and anesthesiologists is assembled. The mother undergoes general anesthesia to relax the uterus and maintain uteroplacental circulation. Delivery: A cesarean section is performed, but the baby remains attached to the placenta and umbilical cord, continuing to receive oxygenated blood from the mother. This can allow up to an hour of oxygenation. Airway Management: While still receiving placental support, the team assesses and secures the baby's airway, which may involve intubation, tracheostomy, or removal of an obstructing mass. Completion: Once the baby's airway is secure and stable, the umbilical cord is cut, and the baby is fully delivered.",
    },
    {
      question: "What syndromes are associated with malformations?",
      sample_answer: "Syndromes associated with vascular and lymphatic malformations include: Sturge-Weber Syndrome: Characterized by a facial port-wine stain, leptomeningeal capillary malformation, and neurological complications. Klippel-Trenaunay Syndrome (KTS): Features capillary, lymphatic, and venous malformations along with limb overgrowth. Parkes Weber Syndrome: Includes arteriovenous malformations in addition to features similar to KTS. PHACE Syndrome: Involves a large segmental facial hemangioma and anomalies of the brain, heart, eyes, and arteries. LUMBAR/SACRAL Syndrome: Associated with lower body hemangiomas and urogenital, anorectal, and spinal anomalies.",
    },
    {
      question: "Describe this photograph. What is your differential diagnosis?",
      sample_answer: "This is a clinical photograph showing a young girl with flat red lesions on her head and chest. I would be suspicous that these represent Port-Wine Stains (Nevus Flammeus): which are flat, vascular malformations present at birth that do not regress and darken over time. In the context of multiple lesions like this, I would be concerned about an associated syndrome such as Sturege-Weber or Klippel-Trenaunay syndrome. Less likely differentials include Capillary haemnagiomas, which are benign vascular tumors that often appear shortly after birth and may undergo a phase of rapid growth before gradually involuting over several years, And Pyogenic Granuloma, which are A rapidly growing, reddish lesion that can appear at any age, often following minor trauma.",
    },
    {
      question: "What is the difference between Sturge Weber syndrome and Klippel Trenaunay syndrome?",
      sample_answer: "Sturge-Weber Syndrome is characterized by a facial port-wine stain (usually affecting one side of the face), leptomeningeal angiomas affecting the brain, and possibly glaucoma. It can result in seizures, developmental delays, and other neurological complications. Klippel-Trenaunay Syndrome (KTS) involves a triad of capillary malformations (port-wine stains), venous malformations, and limb overgrowth. It can also include lymphatic malformations. The symptoms and complications are primarily related to the vascular malformations and limb size discrepancy.",
    },
    {
      question: "How would you treat port wine stains?",
      sample_answer: "Treatment of port-wine stains (PWS) focuses on minimizing their appearance, as these vascular malformations do not regress spontaneously and tend to darken and thicken over time. Treatment options include: Pulsed Dye Laser Therapy: The first-line treatment for PWS, pulsed dye laser therapy, targets the blood vessels within the lesion to lighten the stain. Multiple treatments are usually required, and the effectiveness can vary depending on the location, size, and depth of the PWS. Early treatment, sometimes starting in infancy, is often recommended for best results. Photodynamic Therapy: Involves the use of light-sensitive medication and a light source to destroy abnormal blood vessels. It's an option for lesions that do not respond well to pulsed dye laser therapy. Fractional Laser Therapy: Can be used for treating the thickening of the skin that sometimes occurs with PWS, especially in adulthood. Cosmetics: Specialized makeup and cover-ups can effectively conceal PWS for those seeking a non-invasive option.",
    },
  ],
};
