export const microtiaAndTreacherCollins = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "Please discribe this image",
      sample_answer: "This is a clinical photograph of a child with left sided microtia. This most likely a Weerda grade 3, owing to the lack of subunits and presence of a rudimentary bar. There is likely to be no external auditory canal.",
    },
    {
      question: "What conditions are associated with microtia?",
      sample_answer: "Microtia can be associated with several conditions, with 30% of microtia cases having other abnormalities, though only about 5% of cases are linked to syndromes. Notable associations include Branchio-oto-renal syndrome, Treacher Collins syndrome, Goldenhar syndrome/hemifacial microsomia, exposure to Thalidomide, Foetal alcohol syndrome, and maternal diabetes. Additionally, microtia occurs more frequently in males than in females, tends to be more common on the right side, and is typically unilateral rather than bilateral.",
    },
    {
      question: "What are the important aspects of history and examination in a patient with microtia?",
      sample_answer: "In evaluating a patient with microtia, a comprehensive history should include inquiries about maternal prenatal health and exposures, familial incidence of similar conditions, and the child's developmental milestones, especially relating to hearing and speech. Examination should meticulously assess the extent and severity of the ear deformity, including the development and presence of the ear's anatomical subunits, any craniofacial asymmetry or weakness, and the status of the external auditory canal. It's also crucial to examine the child for signs of associated syndromes, such as features indicative of Treacher Collins syndrome, including zygomatic and mandibular hypoplasia, and other craniofacial anomalies. Attention should also be given to the overall health and development of the child, considering potential associated conditions that could impact management strategies.",
    },
    {
      question: "How do you investigate a child with microtia?",
      sample_answer: "Investigations for a child with microtia are multifaceted, aimed at assessing the extent of hearing loss, evaluating the middle ear and ossicular chain development, and screening for associated anomalies. Auditory assessments like bone conduction auditory brainstem response (ABR) are pivotal for determining the type and degree of hearing loss. Renal ultrasound is recommended for excluding branchio-oto-renal syndrome, while high-resolution CT scans of the temporal bones are indispensable for surgical planning and for evaluating the middle ear's structural development. These investigations not only guide the immediate management, particularly regarding hearing rehabilitation, but also inform decisions about the feasibility and timing of surgical intervention for ear reconstruction.",
    },
    {
      question: "How would you manage a child with microtia?",
      sample_answer: "Management of microtia involves a multidisciplinary team (MDT) approach, encompassing genetics, ENT, plastic surgery, audiology, and prosthetics specialists. Initial management focuses on hearing rehabilitation, utilizing a softband bone conduction device as soon as possible, with progression to a percutaneous bone-anchored hearing aid (BAHA) by age 5 or earlier based on individual assessments. It is important to ensure the placement does not compromise future reconstructive efforts. Surgical reconstruction of the ear is considered based on the child's age, psychosocial factors, and the availability of sufficient autologous material for reconstruction. Generally it is considered when the ear has reached most of its adult size around 6–7 years of age, and costal cartilage is sufficient for grafting by about 10 years, which allows the child's involvment ind decision making and balances physical and psychosocial factors. Surgical reconstruction is typically staged, often requiring minor revisions, and includes options for autologous reconstruction or osseointegrated implants and prostheses. The overarching goal is to address both the cosmetic and functional impacts of microtia, supporting the child's hearing, speech, and social development while considering the family's preferences and expectations.",
    },
    {
      question: "What are the considerations around surgery for microtia?",
      sample_answer: "Surgical intervention for microtia is carefully timed and planned, considering several factors: The ear's developmental stage, typically fully developed by 6-7 years of age, with costal cartilage growth sufficient for grafting around age 10. The severity of the deformity versus the child's age and the psychosocial implications, balancing the need for early intervention with the benefits of waiting until the child can participate in decision-making. The technical aspects of surgery, which usually involves a two-stage process starting with the creation of a new ear framework from rib cartilage, followed by refinement procedures to achieve the best cosmetic and functional outcome. Potential risks and complications, such as pneumothorax from cartilage harvesting, cartilage or skin tissue loss, infection, bleeding, numbness, and scarring.",
    },
    {
      question: "How is microtia classified?",
      sample_answer: "Microtia is classified according to the severity of the ear deformity, guiding the approach to reconstruction and management. The Weerda classification is a commonly used system, distinguishing four grades: Grade I involves all subunits but is mishapen with a normal EAC; Grade II features subunits that are deficient or absent with a present but narrow EAC; Grade III is characterized by a rudimentary bar of tissue with no EAC; and Grade IV, or anotia, indicates the complete absence of the ear and EAC. This classification helps in planning treatment and setting realistic expectations for outcomes.",
    },
    {
      question: "Discuss the surgery for microtia repair.",
      sample_answer: "Surgery for microtia repair is a delicate, staged process focused on creating a new, aesthetically pleasing ear that, as much as possible, resembles a natural ear. The process typically involves: Stage 1: Harvesting rib cartilage to create a new ear framework, reshaping and positioning the lobule, and preparing the site for the new ear, including banking of unused cartilage for future use. Stage 2: Occurring 3-4 months later, involves creating a fascial flap to cover the new framework and applying a skin graft (usually from the scalp) to the area. This stage may also address any additional defects and refine the ear's appearance. Surgical risks include pneumothorax, tissue loss, infection, and scarring, among others, requiring careful planning and discussion with the patient's family about expectations and possible outcomes.",
    },
    {
      question: "What other features on examination of the child would alert you to a diagnosis of Treacher Collins syndrome?",
      sample_answer: "Features indicative of Treacher Collins syndrome include zygomatic and mandibular hypoplasia, colobomas of the lower eyelids, down-slanting palpebral fissures, telecanthus, a prominent nose with a flat malar region, a broad mouth and potentially a cleft palate or other craniofacial anomalies. Examination may also reveal airway anomalies that could necessitate management strategies such as a nasopharyngeal airway or tracheostomy. The presence of these features in conjunction with microtia and ear canal atresia should prompt a comprehensive evaluation for Treacher Collins syndrome, including genetic testing and interdisciplinary consultation to address the complex needs of these patients.",
    },
    {
      question: "What is Treacher Collins syndrome?",
      sample_answer: "Treacher Collins syndrome is an autosomal dominant genetic disorder, which is sporadic in 60% of cases, characterized by craniofacial deformities due to malformations of the first and second branchial arches. It's caused by mutations in the TCOF1 gene on chromosome 5q, coding treacle protein, leading to features such as down-slanting palpebral fissures, maxillary hypoplasia, cleft palate, and ear abnormalities including microtia and atresia. Despite the craniofacial anomalies, intelligence in individuals with Treacher Collins syndrome is typically normal, though hearing loss may contribute to developmental delays.",
    },
    {
      question: "What are the ENT manifestations of Treacher Collins syndrome?",
      sample_answer: "ENT manifestations of Treacher Collins syndrome include auricular deformities ranging from microtia to anotia, atresia or stenosis of the EAC, preauricular fistulas, and malformed ossicles resulting in conductive hearing loss. Other otologic concerns may include bony replacements of the tympanic membrane, widened aqueduct and aberrant facial nerve. It can also affect the airway, with patients presenting with choanal atresia, pierre robin sequence with or without cleft lip and palate or obstructive sleep apnoea.",
    },
    {
      question: "How do you manage the airway of an infant with treacher collins syndrome?",
      sample_answer: "Managing the airway is challenging due to the craniofacial anomalies, particularly mandibular hypoplasia, which can lead to airway obstruction. Effective airway management requires a multidisciplinary approach involving otolaryngologists, anesthesiologists, and pediatric surgeons. Here's how I would manage the airway in such cases: Initial Assessment formed of Comprehensive evaluation of the airway anatomy using imaging studies if necessary, understanding the degree of mandibular hypoplasia and its impact on the airway. Assessment of breathing patterns, especially during sleep, for signs of obstructive sleep apnea (OSA), which is common in these patients. Non-surgical Management include: Positioning: Infants with TCS often breathe more easily when on their stomachs or sides due to gravitational effects on the tongue and mandible. This is especially true during sleep. Continuous Positive Airway Pressure (CPAP) or Bi-level Positive Airway Pressure (BiPAP): These can be considered in mild cases to manage OSA and ensure adequate ventilation. Nasopharyngeal airway: This can be used to bypass airway obstruction caused by glossoptosis or retrognathia. It can be useful in initial management, as an adjunt to other options and as a bridge to surgical management. Surgical Management includes: Tracheostomy In severe cases, where there's significant airway obstruction that cannot be managed conservatively. Mandibular Distraction Osteogenesis: This procedure involves surgical lengthening of the mandible to relieve airway obstruction. It's particularly useful in infants and young children with TCS, improving airway patency by advancing the smaller mandible and thus moving the tongue base forward to open the airway. Tongue-lip adhesion: In cases where the primary issue is glossoptosis (downward or backward displacement of the tongue), this procedure can temporarily alleviate airway obstruction by preventing the tongue from falling back.",
    },
    {
      question: "What is the relationship between aural atresia and microtia?",
      sample_answer: "Aural atresia and microtia often co-occur, with atresia affecting the formation of the EAC and potentially the middle ear structures, while microtia affects the development of the external ear. The degree of external ear malformation in microtia usually correlates with the severity of the middle ear deformity, which in turn impacts the individual's hearing capabilities. This relationship underscores the importance of a comprehensive assessment to guide the management of hearing loss and the planning of any reconstructive surge",
    },
    {
      question: "Discuss the Jahrsdoerfer grading system.",
      sample_answer: "The Jahrsdoerfer grading system is a 10-point scale used to evaluate the surgical candidacy for aural atresia repair based on key anatomical features observed in CT scans and the external ear's appearance. Factors assessed include the presence of the stapes, the openness of the oval window, the development of the middle ear space, the normal positioning of the facial nerve, the presence of the malleus-incus complex, the development of mastoid pneumatization, the connection between the incus and stapes, the presence of the round window, and the formation of the external ear. A score of 8 or above is associated with better postoperative hearing outcomes, indicating a favorable candidate for surgery.",
    },
    {
      question: "Discuss canal atresia surgery.",
      sample_answer: "This is a complex procedure which involves several key steps. The surgery begins with the removal of the bone or soft tissue that constitutes the atresia, carefully crafting an opening to where the EAC should be. Then, Depending on the anatomy and development of the middle ear structures, surgery may involve reconstruction or mobilization of the ossicular chain to restore or improve the mechanism of sound conduction. A new ear canal is then meticulously created, ensuring it is of adequate size and shape for sound transmission and fitted with a skin graft to line the newly formed canal, promoting epithelialization and preventing stenosis. In cases associated with microtia, reconstructive efforts to build or improve the external ear's appearance may coincide with or precede canal creation. Canal atresia surgery, while potentially transformative, carries inherent risks and possible complications, including: Variable success rate in achieving functional hearing improvement. Not all patients will achieve a closed air-bone gap or normal hearing levels post-surgery. Facial Nerve Injury: Given the proximity of the facial nerve to the surgical site, there's a risk of temporary or permanent facial nerve weakness or paralysis. Canal Stenosis: The newly created ear canal may narrow over time, necessitating further surgical intervention. Graft Failure: The skin graft lining the new canal may not take successfully, leading to exposed bone and potential chronic drainage or infection. Chronic Otitis Externa: The presence of a new ear canal can predispose to infections, requiring ongoing medical management.",
    },
  ],
};
