export const NeckDissection = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "What is going on in this picture?",
      sample_answer: "This is a clinical photograph of a patient undergoing a neck dissection. It appears the sternocleidomastoid muscle has been cut, making it at least a modified radical neck dissection.",
    },
    {
      question: "What is a neck dissection?",
      sample_answer: "A neck dissection is a surgical procedure that involves the removal of lymph nodes and potentially other structures in the neck. This operation is primarily indicated for the management of lymph node metastases from head and neck cancers. It aims to remove cancerous nodes, assess the extent of disease spread, and prevent further progression of cancer. The procedure varies from conservative approaches that preserve many of the non-lymphatic structures to more extensive dissections where additional muscles, nerves, and veins may be removed if they are involved by the tumor.",
    },
    {
      question: "How are neck dissections classified?",
      sample_answer: "Neck dissections are classified based on the extent of removal of lymph nodes and the preservation of non-lymphatic structures: Radical Neck Dissection (RND): This involves the removal of all lymph nodes from levels I to V, along with the sternocleidomastoid muscle, internal jugular vein, and spinal accessory nerve. It's used for extensive nodal disease with suspected involvement of these structures. Modified Radical Neck Dissection (MRND): Similar to RND but spares one or more non-lymphatic structures (spinal accessory nerve, internal jugular vein, sternocleidomastoid muscle). It’s classified further into Type I, II, and III, depending on what is preserved. Selective Neck Dissection (SND): This involves removing only specific lymph node groups that are at risk, based on the primary tumor's location, thus preserving muscle, nerve, and vein structures. Variants include supraomohyoid, lateral, and posterolateral neck dissections, each targeting different groups of lymph nodes. Extended Neck Dissection: This involves the removal of additional lymph node groups or non-lymphatic structures not typically included in a more radical neck dissection, such as parts of the hypoglossal nerve, the parotid gland, or certain muscles, depending on tumor spread. They can also be classified according their indication, with elective neck dissection being done to an N0 neck, compared to therapeutic neck dissection when disease is present.",
    },
    {
      question: "Tell me about the classification of modified radical neck dissections.",
      sample_answer: "Modified Radical Neck Dissection (MRND) is classified into three types based on the non-lymphatic structures that are preserved: Type I MRND: Preserves the spinal accessory nerve but removes the sternocleidomastoid muscle and internal jugular vein. Type II MRND: Preserves both the spinal accessory nerve and the internal jugular vein, but removes the sternocleidomastoid muscle. Type III MRND (also known as the Functional Neck Dissection): Preserves the spinal accessory nerve, internal jugular vein, and sternocleidomastoid muscle. Each type is chosen based on the extent of cancer spread and the need to maintain functional outcomes while effectively managing the disease.",
    },
    {
      question: "When would a radical neck dissection be indicated?",
      sample_answer: "A radical neck dissection is indicated when there is extensive metastatic neck disease involving multiple lymph node levels, especially when these nodes show extracapsular spread (ECS) and involve adjacent non-lymphatic structures such as the sternocleidomastoid muscle, internal jugular vein, or the spinal accessory nerve. It is typically reserved for cases where less extensive surgeries are unlikely to achieve adequate disease control due to the aggressiveness or advanced stage of the cancer.",
    },
    {
      question: "Tell me about the different types of selctive neck dissection and when they are used",
      sample_answer: "The type of SND performed depends on the primary cancer site and the expected pattern of lymph node metastasis: Supraomohyoid Neck Dissection: Removes lymph nodes in Levels I, II, and III. It is typically used for cancers of the oral cavity where these levels are most likely to contain metastases. Lateral Neck Dissection: Includes lymph nodes from Levels II, III, and IV, and is often used for cancers of the oropharynx, larynx, and hypopharynx. Posterolateral Neck Dissection: Involves the removal of lymph nodes from Levels II through V, and is used primarily for cancers located in the posterior scalp or skin of the neck. Anterior Compartment Neck Dissection: Targets lymph nodes in Level VI and is generally performed for thyroid cancers or other diseases involving the anterior compartment of the neck.",
    },
    {
      question: "Tell me about the 7 neck nodal levels, including their contents and boundaries.",
      sample_answer: "These include: Level 1, divided into 1A and 1B. Level 1A (Submental) is Bound by the anterior bellies of the digastric muscles laterally and the body of the hyoid bone inferiorly. It contains the submental lymph nodes, which drain the lower lip, floor of the mouth, and the tip of the tongue. Level 1B (Submandibular) is Enclosed by the anterior and posterior bellies of digastric and the body of the mandible superiorly. It houses the submandibular gland and lymph nodes, which drain the cheeks, upper lip, lateral parts of the lower lip, anterior nasal cavity, and the teeth and gums. Level 2 (Upper Jugular nodes): Extends from the skull base to the hyoid bone (radiological) or the carotid bifurcation (surgical). It is divided into: Level 2A: Anterior to the spinal accessory nerve, and Level 2B: Posterior to the spinal accessory nerve. Level 3 (Middle Jugular nodes): Located between the inferior boarder of the hyoid bone and the cricoid cartilage (clinical) or the omohyoid muscle (surgical). It drains the pharynx, oral cavity, and larynx. Level 4 (Lower Jugular): Extends from the cricoid cartilage to the clavicle. It drains the lower neck and upper thoracic structures. Level 5 is split into two sub-levels by the inferior border of the cricoid cartilage: Level 5A (Spinal Accessory) is above the plane of the cricoid and bounded by the sternocleidomastoid and the trapezius muscles. It contains lymph nodes along the spinal accessory nerve. Level 5B (Transverse Cervical) is below the cricoid cartilage to the clavicle, containing lymph nodes along the transverse cervical artery and the supraclavicular nodes. Level 6 is Bound laterally by the common carotid arteries, superiorly by the hyoid bone, and inferiorly by the sternal notch. It contains prelaryngeal (Delphian), pretracheal, and paratracheal nodes. It drains the thyroid, larynx, trachea, and esophagus. Level 7 Extends from the suprasternal notch to the innominate artery, and drains the deeper neck and upper thorax.",
    },
    {
      question: "What incisions are used in neck dissection?",
      sample_answer: "The choice of incision in neck dissection depends on the extent of surgery required, aesthetic considerations, and the need for access to specific anatomical regions. Commonly used incisions include: Apron Flap (Gluck): Used for extensive dissections, providing good access to the neck and thorax. Hockey stick: : Useful for extensive dissections involving the neck and parotid area. MacFee: Consists of parallel incisions that offer good cosmetic outcomes. Schobinger: An incision that is placed to provide access while protecting major vessels like the carotid. Conley: An adaptation of the Schobinger incision, modifying the flap placements for better access and potentially better cosmesis. Martin: Provides extensive access with its double Y configuration, useful for access to the supraclavicular area.",
    },
    {
      question: "When are neck dissections performed?",
      sample_answer: "Neck dissections are performed either electively, for patients with clinically negative necks (N0) but a high risk (>15-25%) of occult metastasis, or therapeutically, for those with clinically positive nodes. Elective neck dissections are considered when the primary site has a high incidence of nodal metastases, such as in cancers of the oral cavity, oropharynx, and hypopharynx. Therapeutic dissections are performed when metastatic nodes are confirmed through clinical examination or imaging.",
    },
    {
      question: "When is level 2b dissected?",
      sample_answer: "Level 2b is dissected when there is clinically positive disease noted in adjacent nodal stations, or in specific cancers such as those involving the parotid gland, oral tongue, and hypopharynx. Dissecting this level is crucial as it may harbor metastatic disease, but it carries a risk of accessory nerve damage, which can lead to shoulder dysfunction.",
    },
    {
      question: "What are the risks of neck dissection?",
      sample_answer: "Complications of neck dissection can be categorized into early, intermediate, and late stages, with each stage divided into local and general complications: Early local Complications include: Bleeding Airway Obstruction: Swelling or hematoma may obstruct the airway. Increased Intracranial Pressure due to venous outflow obstruction. Carotid Sinus Syndrome: Triggered by manipulation of the carotid sinus leading to heart rate and blood pressure issues. Nerve Injury: Damage to cranial nerves such as the marginal mandibular, accessory, hypoglossal, vagus, and phrenic nerves, as well as the brachial plexus, resulting in various dysfunctions like vocal changes, shoulder drop, or respiratory issues. Stroke: Injury to the carotid artery can lead to stroke. Early General complications include: Pneumothorax and General Anesthesia Complications such as reactions to anesthesia. Local Intermediate Complications include: Seroma, Chyle Leak, Infection and Wound Dehiscence, Carotid Artery Rupture and Fistula Formation: These can occur due to infection or erosion by a tumor. Intermediate General complications include: Bronchopneumonia, Basal Collapse and Deep Vein Thrombosis (DVT). Local Late Complications include Hypertrophic or Keloid Scarring, Shoulder Dysfunction: Due to spinal accessory nerve injury, leading to issues such as shoulder drop and winged scapula. Chronic Pain and Neuropathies: Ongoing pain and sensory abnormalities due to nerve damage. Late General complications include Lymphedema and Functional Disabilities related to nerve damage, including vocal changes and swallowing difficulties.",
    },
    {
      question: "What are the landmarks for the spinal accessory nerve?",
      sample_answer: "The key landmarks and guidance for locating the spinal accessory nerve during surgery include: Sternocleidomastoid Muscle (SCM): The nerve typically enters the sternocleidomastoid muscle at the junction of the upper and middle thirds of the muscle. The point of entry is a reliable landmark and is critical during the initial stages of the dissection to avoid inadvertent injury. Erb’s Point: This is an important anatomical landmark located roughly two to three centimeters caudal to the mastoid process along the posterior border of the SCM. The spinal accessory nerve can be identified here as it emerges from the muscle before it enters the trapezius. Internal Jugular Vein (IJV): The nerve crosses either superficial or deep to the IJV in the cervical region. This crossing typically occurs in the upper neck, and identifying this relationship helps in tracing the nerve’s path safely. Transverse Cervical Artery: Often, the nerve crosses the transverse cervical artery, which can serve as a guide to the nerve’s location. The artery may either cross above or below the nerve, and this variation must be noted during dissection. Relation to C1 Transverse Process: Proximally, near the base of the skull, the nerve runs close to the transverse process of C1 (atlas). This bony landmark can help in identifying the nerve's path as it descends into the neck. Overlying Perforator Vessel: At times, a perforating vessel may overlie the nerve. Care must be taken to manage these vessels without damaging the nerve. Deep to Posterior Belly of Digastric Muscle: As the nerve travels superficially in the neck, it is located deep to the posterior belly of the digastric muscle, which can serve as a guide for its upper segment.",
    },
    {
      question: "What are the differences between pathological and clinical nodal staging?",
      sample_answer: "Pathological nodal staging (pN) involves examining surgically removed nodes to assess the extent of metastasis, providing precise staging that influences prognosis and further treatment. It includes counting the number of affected nerves and identifying and extranodal extension. Clinical nodal staging (cN), derived from imaging and physical exams, assesses node size, number, and the presence of extranodal extension, used for initial diagnostic and treatment planning.",
    },
    {
      question: "Tell me about the fixed neck.",
      sample_answer: "A 'fixed neck' refers to situations where lymph nodes or tumor masses are adherent to critical structures like the vertebrae, carotid artery, or brachial plexus, making them difficult or impossible to remove surgically without significant risk. These cases might require initial treatment with chemotherapy and radiation to reduce the tumor size, potentially converting an unresectable tumor into a resectable one, if appropriate.",
    },
    {
      question: "How do you perform your neck dissection?",
      sample_answer: "In an anaesthetised patient, the head should be extended and turned away from the side of the dissection to expose the neck area maximally. I use a hockey stick incision to allow adequate exposure while preserving blood supply to the skin flaps. I Carefully elevate the skin and subcutaneous tissue flaps using sharp and blunt dissection. I then Proceed with the dissection of lymph node levels as determined preoperatively: Identify and protect the spinal accessory nerve, especially when dissecting level IIb. Continue with the removal of lymph nodes from each involved level, ensuring all fibrofatty tissue within the designated levels is cleared. Use landmarks such as the sternocleidomastoid muscle, internal jugular vein, and carotid artery to guide the dissection and prevent injury to these structures. Management of Vital Structures: Depending on the type of neck dissection: In a radical neck dissection, remove the sternocleidomastoid muscle, internal jugular vein, and spinal accessory nerve if involved by disease. In a modified radical neck dissection, preserve one or more of these non-lymphatic structures as clinically indicated. In selective neck dissections, focus on removing only the lymph node groups at high risk of metastasis, preserving all other structures. Hemostasis: Achieve meticulous hemostasis throughout the procedure to prevent postoperative hematoma formation. Use ligatures and electrocautery as necessary to control bleeding from small vessels. Closure and Drainage: Insert a surgical drain to prevent fluid accumulation in the dissected space. Close the surgical site in layers to support healing and reduce tension on the skin edges. Use absorbable sutures for deeper layers and non-absorbable sutures or staples for skin closure.",
    },
  ],
};
