export const oralCancer = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "Please describe this image",
      sample_answer: "This is a clinical photograph showing an irregular, ulcerated lesion on the lateral boarder of the tongue on the right side.",
    },
    {
      question: "What is your differential diagnosis?",
      sample_answer: "my differential diagnosis would span across various categories including infectious, traumatic, and neoplastic causes: Infectious Causes: This includes viral infections such as herpes simplex virus presenting as painful ulcers, and bacterial infections which might result from poor oral hygiene leading to opportunistic infections. Traumatic Causes: Repeated mechanical trauma, such as biting or irritation from sharp edges of teeth or dental appliances, can cause chronic ulcers. Chemical burns from acidic or caustic substances ingested inadvertently can also lead to ulceration. Benign Neoplastic Causes: These include benign tumors like fibromas or papillomas that might occasionally ulcerate due to trauma. Malignant Neoplastic Causes: Squamous cell carcinoma (SCC) is the most common malignancy of the oral cavity, accounting for about 90% of cases. Less common malignancies include basal cell carcinoma (especially on the lip), malignant melanoma, and various types of sarcomas and salivary gland cancers.",
    },
    {
      question: "What would you inquire about during your history taking for this patient?",
      sample_answer: "During history taking, my focus would encompass the following areas: Symptoms and Course: I would inquire about the duration, progression, and associated symptoms (pain, bleeding) of the ulcer. Questions about recent changes in size, color, or pain level can provide clues to its nature. Risk Factors: Understanding the patient's exposure to risk factors such as tobacco use, alcohol consumption, betel nut chewing, and history of HPV infection is critical. Additionally, I'd ask about previous history of similar lesions or oral conditions like leukoplakia or erythroplakia. Red flag symptoms: I would enquire about unintentional weight loss, unilateral otalgia, dysphagia and odynophagia. Dental History: Information on recent dental procedures, the presence of ill-fitting dentures, or history of trauma to the oral cavity could indicate a traumatic cause for the ulcer. Medical History: A comprehensive review of the patient’s past medical history, including any history of cancers, particularly head and neck cancers, and their treatments (radiation or chemotherapy), would be essential. Social history would include enquiry about occupational exposures. Family History: Inquiring about a family history of cancer could suggest a genetic predisposition.",
    },
    {
      question: "What would you look for during your examination of this patient?",
      sample_answer: "My examination would be methodical and include: Local Examination: I'd closely inspect the ulcer, noting its size, depth, margins, and any signs of induration or bleeding. I'd also examine the entire oral cavity for any other lesions, white patches (leukoplakia), red patches (erythroplakia), or masses. Palpation: Palpating the ulcer and surrounding tissues to assess for firmness or fixation to underlying structures, which could suggest malignancy. Additionally, palpating the neck for lymphadenopathy is crucial as it may indicate metastasis. Functional Assessment: Evaluating the patient's oral functions, including speech, swallowing, and jaw movement, can reveal the impact of the lesion and suggest involvement of deeper structures. Flexible nasendoscopy to allow me to examine for synchronous lesions and assess the airway. Systemic Examination: A general examination to look for signs of systemic disease that may present with oral manifestations, including nutritional deficiencies or autoimmune conditions.",
    },
    {
      question: "What investigations would you undertake for this patient?",
      sample_answer: "Imaging Studies: MRI of the oral cavity is preferred for its superior soft tissue contrast, which is invaluable in assessing the extent of a neoplastic lesion. CT scans can provide detailed information on bone involvement. Ultrasound of the neck, possibly with fine needle aspiration (FNA) of suspicious lymph nodes, would be useful for assessing nodal disease. I would do this before performing my biopsy, which I tend to do as an incisional or punch biopsy at panednoscopy in theatre, though I am aware some do this in clinic. Panoramic Radiography (OPG): Useful for assessing the status of the teeth and jawbone, especially if there's suspicion of bone invasion by the lesion. Blood Tests: To evaluate the patient’s general health status, nutritional status, and to screen for markers of infection or inflammation. HPV Testing: For lesions suspicious for SCC, testing for high-risk HPV types can be informative given the association with oropharyngeal cancers.",
    },
    {
      question: "What are the oral cavity subsites affected by cancer and what is the frequency at each subsite?",
      sample_answer: "Cancer can affect various subsites within the oral cavity, each with a different frequency of occurrence: Tongue: The most common site for oral cavity cancers, particularly the lateral borders and the ventral surface. Floor of Mouth: The second most common site, prone to early spread due to its thin mucosa and rich lymphatic network. Lips: Mostly the lower lip, related to sun exposure; cancers here have a better prognosis due to earlier detection and lower tendency for deep invasion. Buccal Mucosa: Less commonly affected but can be associated with chewing tobacco and betel nut use. Hard Palate and Alveolar Ridge: These areas are less frequently involved but can be sites of aggressive cancers, often related to poor dental health and chronic irritation.",
    },
    {
      question: "Outline the T staging for oral cavity cancers.",
      sample_answer: "T1 tumors are ≤2 cm in greatest dimension with ≤5 mm depth of invasion (DOI). T2 tumors are either >2 cm but ≤4 cm in greatest dimension with ≤10 mm DOI, or any tumor with DOI >5 mm and ≤10 mm. T3 includes tumors >4 cm in greatest dimension or any tumor with >10 mm DOI. T4a represents moderately advanced local disease with invasion into adjacent structures such as cortical bone, inferior alveolar nerve, floor of the mouth, or skin of the face for lip cancers, and through cortical bone of the mandible or maxilla, maxillary sinus, or skin of the face for oral cavity cancers. T4b tumors invade masticator space, pterygoid plates, skull base, or encase the internal carotid artery.",
    },
    {
      question: "Outline the N staging for oral cavity cancers.",
      sample_answer: "N0 indicates no regional lymph node metastasis. N1 describes metastasis in a single ipsilateral lymph node ≤3 cm without extranodal extension. N2a involves a single ipsilateral node >3 cm but ≤6 cm. N2b includes multiple ipsilateral nodes, none >6 cm. N2c represents bilateral or contralateral nodes, none >6 cm. N3a is a single node >6 cm, and N3b involves any node(s) with clinically overt extranodal extension.",
    },
    {
      question: "How will you manage a T2N0 lateral tongue SCC?",
      sample_answer: "For a T2N0 lateral tongue SCC, surgical resection of the primary tumor with adequate margins is the primary treatment, aiming for a clinical clearance of ideally 1 cm. Elective neck dissection of levels I–III would be recommended due to the high risk of occult metastasis associated with oral cavity cancers. Reconstruction may be necessary depending on the defect size post-resection. Adjuvant therapy is considered based on final pathology; especially if there are high-risk features such as perineural invasion or close margins. The decision for adjuvant therapy would be made within a multidisciplinary team context, weighing the benefits against potential morbidity. however, in a T2N0 scenario without high-risk features, observation with close follow-up might be sufficient.",
    },
    {
      question: "What factors influence whether or not you give radiotherapy?",
      sample_answer: "The decision to administer radiotherapy is influenced by several factors: Tumor Stage and Features: Advanced stage tumors, tumors with high-risk histopathological features (like perineural invasion, lymphovascular invasion, and close or positive margins), and presence of lymph node metastases are more likely to benefit from radiotherapy. Patient Factors: The patient’s overall health, ability to tolerate radiotherapy, and personal preferences play a critical role in decision-making. Surgical Outcomes: The completeness of surgical resection and the surgical margins influence the need for adjuvant radiotherapy. Presence of Extracapsular Spread: Extracapsular spread in lymph node metastasis significantly increases the risk of recurrence and is a strong indication for adjuvant radiotherapy, often combined with chemotherapy.",
    },
    {
      question: "How do you manage the neck in oral cavity cancers?",
      sample_answer: "Management of the neck in oral cavity cancers is tailored to the clinical and pathological staging: Clinically N0 Neck: For early-stage primary tumors without clinical evidence of nodal involvement, an elective neck dissection of levels I–III is recommended due to the significant risk of occult metastasis. Sentinel lymph node biopsy is an alternative in select cases to stage the neck and decide on the need for further neck dissection. Clinically Node-Positive Neck: Therapeutic neck dissection, including at least levels I–III and possibly IV depending on the primary tumor location and extent of nodal disease, is warranted. The extent of neck dissection may be modified based on intraoperative findings and preoperative imaging. Adjuvant Therapy: Following neck dissection, the need for adjuvant therapy (radiotherapy with or without chemotherapy) is evaluated based on pathological findings such as the number of positive nodes, extracapsular spread, and the presence of high-risk features in the primary tumor.",
    },
    {
      question: "In what situations do you use chemotherapy?",
      sample_answer: "Chemotherapy is utilized in the management of oral cavity cancers in several contexts: Adjuvant Setting: Combined with radiotherapy (chemoradiotherapy) for high-risk features post-surgery, such as positive margins or extracapsular spread in lymph node metastases. Advanced Disease: For unresectable tumors or as palliative treatment in metastatic disease to control symptoms and possibly improve quality of life. Neoadjuvant Setting: Although less common, chemotherapy may be used before surgery to reduce tumor size and make surgical resection more feasible or to assess the tumor's responsiveness to chemotherapy.",
    },
    {
      question: "What are the surgical approaches to oral cavity cancers and when are they used?",
      sample_answer: "Surgical approaches to oral cavity cancers vary with the tumor's location, size, and stage: Transoral Resection: This is the preferred method for early-stage, accessible tumors. By directly accessing the tumor through the mouth, this approach aims to minimize patient morbidity while preserving critical functions such as speech and swallowing. It's particularly suitable for smaller tumors where a complete resection can be achieved without the need for more invasive access. Transoral Laser Microsurgery (TLM): TLM is a minimally invasive technique that employs a laser to precisely cut and remove the tumor tissue. Its advantage lies in the precision of the cut, reducing damage to surrounding healthy tissues, and thereby lessening postoperative pain and speeding recovery. It's most effective for select tumors, offering excellent control with reduced morbidity. Mandibulotomy: This surgical technique involves cutting the lower jaw to gain better access to tumors located in difficult-to-reach areas of the oral cavity or oropharynx. Though it provides extensive access for tumor removal, it requires careful reconstruction of the mandible and soft tissues to preserve cosmetic and functional outcomes. It's indicated for larger tumors or those where transoral access is insufficient. Mandibulectomy: This entails partial or total removal of the mandible (lower jaw) depending on the tumor's involvement. A segmental mandibulectomy removes a tumor-involved section of the jaw, requiring reconstruction for structural and functional restoration. A marginal mandibulectomy, on the other hand, spares the mandible's continuity by removing only the bone adjacent to the tumor, used for tumors close to but not invading the mandible. This approach is crucial for tumors with direct bony involvement or for ensuring clear margins while preserving as much jaw structure as possible.",
    },
    {
      question: "Tell me about histological margins in oral cavity cancer.",
      sample_answer: "Histological margins are a critical factor in assessing the adequacy of tumor resection: Negative Margins: Ideally, a margin of at least 5 mm of normal tissue around the tumor is aimed for, indicating that the tumor has been completely excised. Positive Margins: Presence of tumor cells at or near the resection margin significantly increases the risk of local recurrence and generally necessitates further treatment, which may include additional surgical resection or adjuvant radiotherapy. Close Margins: These are typically defined as tumor cells within 1-5 mm of the resection edge. The risk of recurrence is higher than with negative margins, and close follow-up or additional treatment may be considered.",
    },
    {
      question: "What are the reconstructive options in oral cavity cancer and when are they used?",
      sample_answer: "Primary Closure: Direct suturing is used for small, superficial defects, offering a straightforward and quick healing process. Local Flaps: Utilized for moderate-sized defects, these involve tissue transferred from an adjacent area, maintaining the original blood supply. Examples include the buccal mucosa flap for intraoral defects and the nasolabial flap for lip reconstruction, valued for their color match and surgical simplicity. Regional Flaps: The pectoralis major myocutaneous flap, used for larger oral cavity and oropharynx defects, is sourced from the same body region but not immediately adjacent to the defect. This method is an alternative when free flap transfer is impractical due to patient comorbidities. Free Flaps: For comprehensive reconstruction, free flaps involve tissue transfer from a distant site, with microvascular anastomosis reestablishing blood supply. Soft Tissue Free Flaps: The radial forearm free flap provides thin, pliable skin and can include a sensory nerve, making it suitable for significant soft tissue reconstruction. Osseous Free Flaps: The fibula free flap is preferred for mandibular reconstructions, offering robust bone for support and a skin paddle for soft tissue needs, with minimal donor site morbidity. Composite Free Flaps: For combined bone and soft tissue requirements, the scapular free flap offers versatility in complex reconstructions. Dental Rehabilitation: Post-reconstruction, dental implants and prosthetics are often necessary to restore full oral function, especially following mandibular reconstructions.",
    },
    {
      question: "What is the prognosis of oral cavity cancer?",
      sample_answer: "The prognosis of oral cavity cancer depends on the stage at diagnosis, histopathological features, and the presence of high-risk factors like extranodal extension and positive margins. Early-stage diseases (stage I and II) have significantly better outcomes, with reported 2-year crude survival rates around 85% and 70%, respectively. Advanced stages (III and IV) have lower survival rates, approximately 50% for stage III and 40% for stage IV non-metastatic disease. The presence of distant metastases (stage IVC) further worsens the prognosis. Effective multidisciplinary management, including surgery, radiotherapy, and chemotherapy, is key to improving survival and quality of life for patients with oral cavity cancer.",
    },
  ],
};
