export const VestibularSchwannoma = {
  intro: "Hello let's start",
  questionAndAnswers: [
    {
      question: "Please describe this image.",
      sample_answer: "This is a contrast enhanced coronal section through a T1 MRI scan showing a left sided enhancing cerebellopontine angle lesion.",
    },
    {
      question: "What is your differential diagnosis for this appearance?",
      sample_answer: "For an MRI scan showing a cerebellopontine angle lesion, I would consider several differential diagnoses categorized based on lesion characteristics visible in MRI imaging—T1, T2, and contrast enhancement behaviors: Schwannomas such as: Vestibular Schwannoma: The most common CPA tumor, typically hypointense on T1 and T2, and brightly enhances with contrast and Originates from the internal auditory canal. Facial Nerve Schwannoma: May involve the facial nerve along its course, often with enlargement of the fallopian canal, enhances with contrast. Meningeal Pathology: Meningioma: Typically homogeneous and often shows calcification with a characteristic dural tail. It is isointense or mildly hypointense on T1, hyperintense on T2, and strongly enhances with gadolinium contrast. Arachnoid Cyst: Matches cerebrospinal fluid signal on all MRI sequences, not enhancing with contrast. Metastasis: Varies based on the primary tumor type but generally enhances with contrast. Often irregular borders and may involve adjacent bone destruction. Skull Base Pathology: Chordoma: Destructive growth with bone involvement, typically shows a heterogeneous enhancement. Chondrosarcoma: May show calcifications, destructive growth patterns, and enhances with contrast. Cisterns and Other Lesions: Epidermoid Cyst: Bright on T2, does not enhance with contrast, sometimes called 'congenital cholesteatomas' of the CPA. Lipoma: Typically very high signal on T1 due to fat content, does not enhance with contrast.",
    },
    {
      question: "What would you inquire about during your history taking for this patient?",
      sample_answer: "I would organize the history taking into several key categories: Auditory Symptoms: I would ask about hearing loss, whether it's gradual or sudden, as this is a common presentation in vestibular schwannomas. Tinnitus and any sensations of fullness in the ear would also be pertinent. Vestibular Symptoms: Questions about vertigo, dizziness, or balance issues, as these may indicate involvement of the vestibular system. Neurological Symptoms: Inquiry about headaches, facial numbness, weakness, or twitching would help assess for cranial nerve involvement. Symptoms like changes in taste or swallowing difficulties could suggest involvement of the glossopharyngeal or vagus nerves. Visual Changes: Specifically, I would ask about symptoms like diplopia or blurred vision which could indicate increased intracranial pressure or brainstem involvement. Family History: Especially pertinent for younger patients, as a history of similar symptoms or known genetic conditions like neurofibromatosis could be highly relevant.",
    },
    {
      question: "What would you look for during your examination of this patient?",
      sample_answer: "During the physical examination, I would focus on several systems: Otologic Examination: Inspection of the external auditory canal and tympanic membrane, checking for any signs of mass effect or other abnormalities. Cranial Nerve Examination: A thorough assessment of all cranial nerves, with particular attention to the trigeminal nerve (facial sensation), facial nerve (muscle movement, symmetry, and taste), acoustic reflexes, and auditory function. Neurological Examination: Assessment of cerebellar function including coordination, gait analysis, and nystagmus which might indicate compression or involvement of the cerebellum or its pathways. Ophthalmologic Examination: Evaluation for papilledema, which could indicate raised intracranial pressure.",
    },
    {
      question: "What investigations would you undertake for this patient?",
      sample_answer: "The following investigations would be essential: Audiometric Testing: To assess the degree and type of hearing loss. Tests like speech discrimination scores and acoustic reflexes would help differentiate cochlear from retrocochlear pathology. On speech testing I would expect to encounter phonemic regression, which is disproportional loss of speech recognition when compared to pure tone thresholds and rollover phenomenon which is reduced speech discrimination scores with increasing sound intensity. On acoustic reflex testing I would expect tone decay, which would manifest as decreased auditory perception with sustained signal testing. Radiological Imaging: MRI with gadolinium contrast remains the gold standard for imaging CPA lesions, providing detailed information about the size, extent, and exact location of the lesion, and its relationship to surrounding structures. CT may be useful where MRI is contraindicated by showing widening of the IAC with bone resorption in vestibular schwannoma or hyperostosis in meningiomas. Auditory Brainstem Response (ABR) is Useful in detecting retrocochlear pathologies such as vestibular schwannomas, particularly when the MRI is inconclusive. IT would show interaural latency on wave 5 or increased latency of waves 1 to 5. Vestibular Function Tests: While less commonly used, they can be beneficial in assessing the functional status of the vestibular system.",
    },
    {
      question: "What is a vestibular schwannoma?",
      sample_answer: "Vestibular schwannoma, also known as acoustic neuroma, is a benign tumor that arises from the Schwann cells covering the vestibular nerve, part of the eighth cranial nerve. These tumors are mostly sporadic, but about 5% are associated with neurofibromatosis type 2 (NF2). They are the most common tumors in the CPA, characterized by their slow growth. The management is primarily dictated by the size of the tumor, its growth rate, and the presence and extent of symptoms, particularly hearing loss.",
    },
    {
      question: "What are the phases of growth for a vestibular schwannoma?",
      sample_answer: "The growth of vestibular schwannomas can typically be described in three phases: Otological Phase: Characterized by symptoms such as unilateral sensorineural hearing loss, tinnitus, and sometimes vertigo. The tumor growth during this phase is usually slow, allowing for potential compensation mechanisms to mitigate vertigo symptoms. Neurological Phase: As the tumor expands, it can cause compression of nearby cranial nerves leading to symptoms like facial numbness or weakness, changes in taste, and swallowing difficulties. Headaches and other signs of brainstem compression may also appear. Terminal Phase: Characterized by symptoms of raised intracranial pressure such as severe headaches, visual disturbances due to papilledema, changes in consciousness, and potentially life-threatening brainstem compression",
    },
    {
      question: "How would you manage a patient with a vestibular schwannoma?",
      sample_answer: "Management of a vestibular schwannoma is informed by the size of the tumor and the patient's hearing status: For Intracanalicular and Small Tumors (<1.5 cm) Management involves observation with serial imaging, starting with an MRI at 6 months regardless of hearing status. If there is no growth observed, MRIs continue annually for 5 years and then every two years to monitor for any late-onset growth. With Demonstrated Growth: If growth is detected on follow-up imaging, stereotactic radiotherapy is considered. For Medium-Sized Tumors (1.5 cm - 3 cm): For medium-sized tumors that show no growth, serial imaging is continued to monitor for any changes. The frequency of imaging would be determined based on the initial size and any potential factors that may suggest a higher risk of growth, but generally follows the same protocol as smaller tumors. With Growth: If there is evidence of tumor growth, stereotactic radiotherapy is the treatment of choice, aiming to prevent further tumor enlargement and preserve neurological function. Those without serviceable hearing have the option of microsurgery regardless of growth status. Large or Giant Tumors (>3 cm): With Normal or Serviceable Hearing and No Growth: In this uncommon scenario, given the size of the tumor and potential risk for brainstem compression, the decision to proceed with surgery may be more pressing. The choice of surgical approach, either retrosigmoid or another appropriate method, would be influenced by the goal of hearing preservation. With No or Non-serviceable Hearing and No Growth: For large tumors, even in the absence of recent growth, the risk of complications due to the size and proximity to critical structures like the brainstem often necessitates surgical intervention, typically via the translabyrinthine approach which provides good access for tumor removal but results in the loss of any residual hearing.",
    },
    {
      question: "What are the different surgical approaches for vestibular schwannoma?",
      sample_answer: "Surgical approaches for vestibular schwannoma include: Translabyrinthine Approach: Ideal for non-hearing preservation cases, allows excellent access to the tumor and early identification of the facial nerve. Disadvantages include a high risk of hearing loss and CSF leaks. Retrosigmoid Approach: Suitable for larger tumors with a potential for hearing preservation. Provides good exposure but may require significant cerebellar retraction, leading to potential complications like headaches and increased operative time. Middle Fossa Approach: Best for small intracanalicular tumors when hearing preservation is possible. Technically challenging and associated with risks such as temporal lobe retraction effects, including seizures.",
    },
    {
      question: "What are the different types of radiotherapy used in Vestibular Schwannoma?",
      sample_answer: "There are two primary radiotherapy options: stereotactic radiosurgery and fractionated stereotactic radiotherapy. Stereotactic Radiosurgery (SRS) such as Gamma Knife or CyberKnife, involves delivering a single high-dose or a few fractionated doses of radiation precisely to the tumor, minimizing exposure to surrounding brain tissue. It's less invasive than surgery, with a relatively low immediate risk profile, and is particularly beneficial for smaller tumors (<3 cm) or for patients who are not good surgical candidates. It is not be effective for larger tumors due to the risk of radiation damage to the surrounding brain structures. It also does not provide immediate relief if the tumor is causing compression symptoms because it does not remove the tumor, only aims to halt its growth. Potential long-term complications include hearing loss, balance problems, facial nerve weakness, and, in rare cases, malignant transformation of the tumor or radiation necrosis. Fractionated Stereotactic Radiotherapy (FSRT) involves delivering radiation in smaller doses over multiple sessions. Techniques such as intensity-modulated radiotherapy (IMRT) or volumetric modulated arc therapy (VMAT) may be employed. The fractionation allows for the normal tissue to recover between treatments, potentially reducing the risk of damage to surrounding structures. It may be more suitable for larger tumors where a high single dose could be harmful. It requires multiple visits to the treatment center, and there's a risk of cumulative radiation exposure to the brain. FSRT is considered for tumors that are larger or have a complex shape, or when the patient's situation necessitates a more gradual treatment approach. Though the risk of acute side effects is lower, there is a risk of long-term effects like hearing loss, balance dysfunction, and the potential for radiation-induced secondary tumors.",
    },
    {
      question: "Tell me about bevacizumab and when it is used in vestibular schwannoma",
      sample_answer: "Bevacizumab (Avastin) is a monoclonal antibody that inhibits vascular endothelial growth factor (VEGF), which can be useful in reducing tumor-induced edema and possibly slowing tumor growth. In the context of vestibular schwannoma, particularly those associated with NF2, it is considered when tumors are aggressive with rapid growth or when other therapeutic options (surgery or radiation) are not suitable or have been exhausted. It may help stabilize hearing loss and slow the progression of tumors, particularly in NF2 patients.",
    },
    {
      question: "How is vestibular schwannoma classified by the British Skull Base Society?",
      sample_answer: "The British Skullbase Society classifies vestibular schwannomas based on their size as measured at the cerebellopontine angle: Intracanalicular (0 mm): Tumors confined to the internal auditory canal. Small (1–15 mm): Tumors that extend slightly into the CPA but remain mostly within the canal. Medium (16–29 mm): Tumors that fill a significant portion of the CPA. Large (30–40 mm): Tumors that are approaching or contacting the brainstem. Giant (>40 mm): Tumors that compress the brainstem and may cause significant neurological deficits.",
    },
    {
      question: "What is neurofibromatosis?",
      sample_answer: "Neurofibromatosis Type 1 (NF1) and Type 2 (NF2) are genetic disorders characterized by the growth of tumors along the nerves, but they have distinct clinical and genetic profiles. Neurofibromatosis Type 1 (NF1) is typically evident in childhood with symptoms such as café-au-lait spots, Lisch nodules in the eyes, and multiple neurofibromas on the skin. NF1 is caused by a mutation in the NF1 gene on chromosome 17, leading to a deficiency in neurofibromin, a tumor suppressor. The presence of six or more café-au-lait spots, two or more neurofibromas, or a plexiform neurofibroma is usually diagnostic for NF1. Neurofibromatosis Type 2 (NF2) presents mainly with central nervous system symptoms, notably bilateral vestibular schwannomas that affect hearing and balance, typically emerging in late adolescence or early adulthood. NF2 also includes other nervous system tumors such as meningiomas, spinal schwannomas, and ependymomas. A distinctive feature of NF2 is the development of juvenile posterior subcapsular lenticular opacities, or cataracts. The genetic mutation for NF2 is on chromosome 22, affecting the merlin protein, another tumor suppressor. Diagnosis is often based on the presence of bilateral vestibular schwannomas or a combination of a unilateral vestibular schwannoma and two of the following: meningioma, glioma, schwannoma, or juvenile cataracts.",
    },
    {
      question: "What are the diagnostic criteria for NF2?",
      sample_answer: "The diagnostic criteria for NF2, according to the National Institutes of Health (NIH), are precise to ensure accurate diagnosis and appropriate management. These include: Bilateral vestibular schwannomas: Diagnosis can be confirmed with the presence of tumors on both auditory nerves, which is highly characteristic of NF2. First-degree relative with NF2 plus either of the following: Unilateral vestibular schwannoma or Any two of the following: Meningioma Glioma Neurofibroma Schwannoma Posterior subcapsular lenticular opacities A patient with no known family history of NF2 must meet one of the following criteria: Multiple meningiomas (two or more) and Unilateral vestibular schwannoma at a young age (before age 30) or Any two of the following: glioma, neurofibroma, schwannoma, cataract",
    },
    {
      question: "What additional features would you expect if the patient had NF2?",
      sample_answer: "In NF2, additional features may include: Multiple meningiomas: These tumors may occur anywhere in the central nervous system. Spinal tumors: Such as schwannomas, meningiomas, or ependymomas. Ocular abnormalities: Including cataracts at a young age, particularly posterior subcapsular type. Cutaneous schwannomas: Which are less common than in NF1 but can occur. Peripheral neuropathies: Due to schwannomas on peripheral nerves. These features significantly impact the approach to treatment and ongoing management of patients with NF2.",
    },
    {
      question: "What additional assessments would you undertake if you suspected the patient had NF2?",
      sample_answer: "If NF2 is suspected, additional assessments would include: Comprehensive neurological examination: To evaluate for signs of other nerve tumors. Ophthalmological assessment: To check for cataracts and other ocular abnormalities that are common in NF2. Audiological evaluation: To assess hearing, particularly for evidence of bilateral vestibular schwannomas. Whole-body MRI: To identify other potential tumors in the CNS and peripheral nerves. Genetic testing: To confirm the diagnosis by detecting mutations in the NF2 gene.",
    },
    {
      question: "How would you manage a neurofibromatosis patient with bilateral vestibular schwannoma?",
      sample_answer: "Managing a patient with Neurofibromatosis Type 2 (NF2) should be undertaken at one of the 2 NF2 centres to ensure the patient who has bilateral vestibular schwannomas receives a comprehensive, individualized approach that takes into account the size and symptoms of the tumors, the patient's age, overall health, and lifestyle needs. They will need regular radiological surveillance with consideration of management with Bevacizumab for growing schwannomas, as well as surgical excision with hearing rehabilitation in the form of cochlear implants or auditory brainstem implants. Given the complex nature of NF2, management often extends beyond the schwannomas themselves. Patients may require treatment for other CNS tumors, cataracts, and skin tumors. Psychological support, genetic counseling, and management of other NF2-related conditions are also integral components of comprehensive care.",
    },
  ],
};
